const test=require('node:test'),assert=require('node:assert/strict');
const {Store}=require('../electron/core.cjs'),{Market}=require('../electron/market.cjs'),{SearchSessions}=require('../electron/search-sessions.cjs'),{Recommendations,profileSignals,document}=require('../electron/recommendations.cjs'),{CarAgent}=require('../electron/agent.cjs'),{WatchChecker}=require('../electron/watches.cjs');
const source={id:'blocket',name:'Blocket',adapter:'blocket-public',enabled:true,mediaAllowed:true,hosts:['www.blocket.se']};
const doc=(id,make='BMW',price=100000)=>({id:String(id),heading:make+' 320d',make,series:'3-Serie',model:'320d',model_specification:'320d',year:2016,mileage:12000,mileage_unit:'SCANDINAVIAN_MILE',transmission:'Automatisk',fuel:'Diesel',sales_form:1,canonical_url:'https://www.blocket.se/mobility/item/'+id,price:{amount:price,currency_code:'SEK'}});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
test('first source cards arrive before a slow source finishes, with session filters enforced',async()=>{const store=await Store.create();store.setSource(source);store.setSource({...source,id:'slow',name:'Slow'});let release;const gate=new Promise(r=>release=r),seen=[],market=new Market(store,{request:async url=>{const n=Number(new URL(url).searchParams.get('page'));return {docs:[doc(n)],metadata:{paging:{last:1}}};}});const original=market.fetchPage.bind(market);market.fetchPage=async(f,o)=>{const fast=await original(f,{...o,sources:['blocket']});await gate;return fast;};const sessions=new SearchSessions(store,market);let finished=false;const result=sessions.start({makes:['BMW'],maxPrice:120000},{onResults:r=>seen.push(r)}).then(r=>{finished=true;return r;});try{await wait(140);assert.equal(finished,false);assert.equal(seen.length,1);assert.equal(seen[0].items[0].make,'BMW');assert.ok(seen[0].sessionId);release();assert.equal((await result).items.length,1);}finally{release();await result;store.db.close();}});
test('cancelled searches never emit pending cards into a new view',async()=>{const store=await Store.create();store.setSource(source);const market=new Market(store,{request:async()=>({docs:[doc(1)],metadata:{paging:{last:1}}})});const original=market.fetchPage.bind(market);market.fetchPage=async(f,o)=>{const result=await original(f,o);await wait(150);return result;};const controller=new AbortController(),seen=[];const pending=new SearchSessions(store,market).start({},{signal:controller.signal,onResults:r=>seen.push(r)});await wait(20);controller.abort();await assert.rejects(pending,{name:'AbortError'});await wait(200);assert.equal(seen.length,0);store.db.close();});
test('personalization combines conversations, manual searches, saves and meaningful usage',async()=>{const store=await Store.create();store.setSource(source);store.importSnapshot(source,{schemaVersion:1,complete:false,listings:[require('../electron/blocket.cjs').parseCar(doc(1))]});new CarAgent({store,market:new Market(store)});const car=store.search().items[0];store.bookmark(car.id);store.recordPreference('search',{filters:{makes:['Audi'],maxPrice:150000}});store.recordPreference('open',{id:car.id,text:document(car)});store.db.run('INSERT INTO chats VALUES (?,?,?,?)',['profile','Önskemål','2026-10-01',JSON.stringify({messages:[{role:'user',text:'Jag vill ha plats för barnvagn och hund.'}],filters:{makes:['Volvo']}})]);const profile=profileSignals(store);assert.deepEqual(profile.groups.map(g=>g.kind),['chattar','sökningar','sparade bilar','bilar du utforskat']);assert.match(profile.groups[0].text,/barnvagn/);assert.equal(profile.filters.makes[0],'Audi');assert.ok(Math.abs(profile.groups.reduce((n,g)=>n+g.weight,0)-1)<1e-9);store.db.close();});
test('watch embeddings rank only strict matches and cache vectors by model variant',async()=>{const store=await Store.create();store.setSource(source);new CarAgent({store,market:new Market(store)});store.importSnapshot(source,{schemaVersion:1,complete:false,listings:[doc(1),doc(2,'Audi'),doc(3,'BMW',250000)].map(require('../electron/blocket.cjs').parseCar)});store.addWatch('Min BMW',{makes:['BMW'],maxPrice:120000});let calls=0;const runtime={cacheKey:'variant-A',embed:async texts=>{calls++;return texts.map(()=>[1,0]);}};const recommendations=new Recommendations({store,runtime,sessions:{}}),ids=store.search().items.map(c=>c.id);const checker=new WatchChecker({store,recommendations,sessions:{start:async()=>({items:store.search().items,sessionId:'test'}),sessions:new Map([['test',{ids:new Set(ids)}]])}});await checker.check();const watch=store.watches()[0];assert.equal(watch.items.length,1);assert.equal(watch.items[0].make,'BMW');assert.equal(watch.items[0].recommendation.model,'google/embeddinggemma-2');const count=calls;await checker.check();assert.equal(calls,count);runtime.cacheKey='variant-B';await checker.check();assert.ok(calls>count);store.db.close();});
