const test=require('node:test'),assert=require('node:assert/strict');
const {Store}=require('../electron/core.cjs');const {validateFilters,normalizeBody}=require('../electron/filters.cjs');
const {resolvePlace,lookupPlaces,distanceKm,aiFilters}=require('../electron/geography.cjs');const {CarAgent}=require('../electron/agent.cjs');
const {Market,sourceGroups}=require('../electron/market.cjs'),{SearchSessions}=require('../electron/search-sessions.cjs');
const {buildURL}=require('../electron/blocket.cjs'),{manualIntent}=require('../electron/search-intent.cjs');
const {parseWebListing,WebListings}=require('../electron/web-listings.cjs');
const source={id:'cars',name:'Bilar',enabled:true,hosts:['cars.example'],mediaAllowed:true};
const base={id:'1',title:'Volvo V70 Business',make:'Volvo',model:'V70',variant:'Business',price:55000,year:2012,mileage:18000,fuel:'Diesel',gearbox:'Automat',bodyType:'estate',city:'Göteborg',sellerType:'dealer',url:'https://cars.example/1',images:['https://cars.example/1.jpg']};
const setup=async ads=>{const store=await Store.create();store.setSource(source);store.importSnapshot(source,{schemaVersion:1,complete:false,listings:ads});return store;};
const schema={ '@context':'https://schema.org','@type':'Car',name:'Volvo V70 Business',brand:{name:'Volvo'},model:'V70',vehicleModelDate:'2012',vehicleConfiguration:'Business',vehicleTransmission:'Automat',fuelType:'Diesel',mileageFromOdometer:{value:180000,unitCode:'KMT'},image:'https://dealer.example/car.jpg',offers:{price:'55000',priceCurrency:'SEK',availability:'https://schema.org/InStock',seller:{'@type':'AutoDealer',name:'Riktig handlare',address:{addressLocality:'Göteborg'}}}};
const html=d=>'<script type="application/ld+json">'+JSON.stringify(d)+'</script>';
test('advanced filters retain custom brands and reject contradictory intervals',()=>{assert.deepEqual(validateFilters({makes:['Okänt bilmärke','okänt bilmärke'],minMileage:0,bodyTypes:['Halvkombi']}),{makes:['Okänt bilmärke'],minMileage:0,bodyTypes:['Halvkombi']});assert.throws(()=>validateFilters({minMileage:9000,maxMileage:8000}));assert.throws(()=>validateFilters({sort:'distance'}));assert.equal(normalizeBody('Halvkombi'),'Halvkombi');});
test('offline Swedish places cover large and small towns, accents and actual distances',()=>{const got=resolvePlace('Göteborg'),stock=resolvePlace('Stockholm'),small=resolvePlace('Överkalix');assert.ok(small);assert.equal(lookupPlaces('Göte')[0].label,'Göteborg');const km=distanceKm(got.latitude,got.longitude,stock.latitude,stock.longitude);assert.ok(km>390&&km<410);assert.equal(distanceKm(null,0,0,0),null);assert.deepEqual(aiFilters({location:{label:'Göteborg',latitude:57.7,longitude:11.97,radiusKm:100}}),{location:{label:'Göteborg',radiusKm:100}});});
test('distance sort and strict radius exclude unknown locations while details remain accurate',async()=>{const s=await setup([base,{...base,id:'2',city:'Stockholm',price:45000},{...base,id:'3',city:'Okänd plats',price:40000}]);const location={label:'Göteborg',radiusKm:50};const r=s.search({location,sort:'distance'});assert.equal(r.total,1);assert.equal(r.items[0].city,'Göteborg');assert.equal(r.items[0].distanceKm,0);const all=s.search({location:{label:'Göteborg'},sort:'distance'});assert.deepEqual(all.items.map(c=>c.city),['Göteborg','Stockholm','Okänd plats']);s.db.close();});
test('seller, body, images, source and minimum mileage compose without confusing hatchbacks and estates',async()=>{const s=await setup([base,{...base,id:'2',bodyType:'Halvkombi',sellerType:'private',images:[]}]);assert.equal(s.search({bodyTypes:['Kombi'],sellerType:'dealer',hasImages:true,sources:['cars'],minMileage:17000,maxMileage:19000}).total,1);assert.equal(s.search({bodyTypes:['Halvkombi']}).total,1);assert.equal(s.search({sources:['missing']}).total,0);s.db.close();});
test('unsupported source brands are sent as queries and mixed known brands are retrieved separately',()=>{assert.match(new URL(buildURL({makes:['Nytt märke'],models:['Modell Z']})).searchParams.get('query'),/Nytt märke Modell Z/);const groups=sourceGroups({makes:['BMW','Nytt märke']},'blocket-public');assert.deepEqual(groups.map(g=>g.makes),[['BMW'],['Nytt märke']]);assert.ok(require('../electron/search-query.cjs').makes.includes('BYD'));});
test('ordinary search translates price, Swedish mil and transmission instead of requiring those words in ads',()=>{assert.deepEqual(manualIntent({query:'V70 business under 60 000 kr och max 20 000 mil automat'}),{query:'V70 business',maxPrice:59999,maxMileage:20000,gearbox:'Automat'});});
test('chat search indexes existing messages, accents, titles and deletion locally',async()=>{const s=await setup([base]),a=new CarAgent({store:s,key:()=>null,emit:()=>{}});a.save({id:'c1',title:'Min nästa bil',messages:[{role:'user',text:'V70 Business nära Göteborg'}],cars:[],filters:{}});a.save({id:'c2',title:'Toyota',messages:[{role:'user',text:'Hybrid i Umeå'}],cars:[],filters:{}});assert.deepEqual(a.list('business goteborg').map(c=>c.id),['c1']);assert.deepEqual(a.list('toyota').map(c=>c.id),['c2']);assert.equal(a.list('% OR 1=1').length,0);a.remove('c1');assert.equal(a.list('business').length,0);s.db.close();});
test('local resorting keeps the fetched cohort and continues the original source cursor without re-fetching',async()=>{const s=await Store.create(),src={id:'blocket',name:'Blocket',enabled:true,hosts:['www.blocket.se'],mediaAllowed:true,adapter:'blocket-public'};s.setSource(src);let reads=0;const request=async url=>{reads++;const p=Number(new URL(url).searchParams.get('page'));return {docs:Array.from({length:50},(_,i)=>({id:p+'-'+i,heading:'Volvo V70',make:'Volvo',series:'V70',year:2012,mileage:18000,mileage_unit:'SCANDINAVIAN_MILE',fuel:'Diesel',transmission:'Automatisk',price:{amount:100000-i,currency_code:'SEK'},canonical_url:'https://www.blocket.se/'+p+'-'+i,sales_form:1})),metadata:{paging:{last:3}}};};const sessions=new SearchSessions(s,new Market(s,{request}));const first=await sessions.start({sort:'newest'});const sorted=sessions.refine(first.sessionId,{sort:'priceAsc'});assert.equal(reads,1);assert.equal(sorted.items[0].price,99951);assert.equal(sorted.total,50);const next=await sessions.next(first.sessionId,sorted.items.map(c=>c.id));assert.equal(reads,2);assert.equal(next.filters.sort,'priceAsc');assert.equal(next.items.length,48);s.db.close();});
test('web cards use original structured values, preserve unknowns and reject sold, lease and listing pages',()=>{const ad=parseWebListing(html(schema),'https://dealer.example/car-1');assert.equal(ad.mileage,18000);assert.equal(ad.price,55000);assert.equal(ad.city,'Göteborg');assert.equal(ad.webDiscovered,true);const missing=parseWebListing(html({...schema,vehicleModelDate:undefined,mileageFromOdometer:undefined}),'https://dealer.example/car-1');assert.equal(missing.year,null);assert.equal(missing.mileage,null);for(const data of [{...schema,name:'Volvo leasing 2 500 kr/mån'},{...schema,offers:{...schema.offers,availability:'https://schema.org/SoldOut'}},[schema,{...schema,name:'Annan bil'}]])assert.equal(parseWebListing(html(data),'https://dealer.example/car-1'),null);assert.equal(parseWebListing(html(schema),'https://bilweb.se/car-1'),null);assert.equal(parseWebListing('<h1>Volvo V70 55000kr</h1>','https://dealer.example/car-1'),null);});
test('web discovery imports real parsed ads into the shared database and cannot bypass strict filters',async()=>{const s=await setup([]);const web={search:async(_q,options)=>{assert.equal(options.mode,'listings');return {sources:[{url:'https://dealer.example/car-1'}]};}};const discover=new WebListings({store:s,web,request:async()=>html(schema)});const found=await discover.find('Volvo V70',{maxPrice:60000});assert.equal(found.cars.length,1);assert.equal(found.cars[0].source,'Riktig handlare');assert.equal(found.cars[0].offers[0].url,'https://dealer.example/car-1');const filtered=await discover.find('Volvo V70',{maxPrice:50000});assert.equal(filtered.cars.length,0);s.db.close();});
test('only real retrieved candidates may be handpicked, with reasons preserved after chat reload',async()=>{const s=await setup([base,{...base,id:'2',price:95000}]);const a=new CarAgent({store:s,key:()=>null,emit:()=>{}}),cars=s.search().items,chat={id:'pick',title:'V70',messages:[],cars:[],searchCars:cars,filters:{maxPrice:60000}};const options={signal:new AbortController().signal,emit:()=>{},activity:()=>({}),message:{}};await assert.rejects(a.execute('select_cars',{selections:[{id:'made-up',reason:'Fin bil'}]},chat,options));await assert.rejects(a.execute('select_cars',{selections:[{id:cars.find(c=>c.price===95000).id,reason:'Billig'}]},chat,options));const good=cars.find(c=>c.price===55000);await a.execute('select_cars',{selections:[{id:good.id,reason:'Business inom din budget.'}]},chat,options);assert.equal(chat.cars.length,1);a.save(chat);assert.equal(a.get('pick').cars[0].selectionReason,'Business inom din budget.');s.db.close();});
test('Bilweb migration disables old listings while preserving saved cars and original details',async()=>{const s=await Store.create(),old={...source,id:'bilweb'};s.setSource(old);s.importSnapshot(old,{schemaVersion:1,complete:false,listings:[base]});const car=s.search().items[0];s.bookmark(car.id);s.removeSource('bilweb');assert.equal(s.search().total,0);assert.equal(s.sources().some(x=>x.id==='bilweb'),false);assert.equal(s.detail(car.id).active,false);assert.equal(s.detail(car.id).saved,true);s.db.close();});
test('filtering a 5000-ad cohort stays local and avoids per-card source queries',async()=>{const s=await setup(Array.from({length:5000},(_,i)=>({...base,id:String(i),price:50000+i,city:i%2?'Stockholm':'Göteborg'})));let reads=0;const sources=s.sources.bind(s);s.sources=()=>{reads++;return sources();};const started=performance.now();const r=s.search({location:{label:'Göteborg',radiusKm:100},sort:'priceAsc',bodyTypes:['Kombi'],hasImages:true});const ms=performance.now()-started;assert.equal(r.total,2500);assert.equal(r.items.length,48);assert.equal(reads,1);assert.ok(ms<1000,'local search took '+ms.toFixed(1)+'ms');console.log('5000-ad filter benchmark: '+ms.toFixed(1)+' ms');s.db.close();});

test('source radius uses actual supported county filters and avoids unsupported source sort enums',()=>{const u=new URL(buildURL({location:{label:'Göteborg',radiusKm:50},sort:'mileage',minMileage:5000}));assert.ok(u.searchParams.getAll('locations').includes('VASTRA_GOTALAND'));assert.equal(u.searchParams.get('sort_order'),'PUBLISHED_DESC');assert.equal(u.searchParams.get('milage_from'),'5000');});

test('natural-language location and distance are real constraints while coordinates stay out of model filters',()=>{const {userIntent}=require('../electron/search-intent.cjs');const f=userIntent(['Hitta BMW nära Göteborg inom 10 mil']);assert.equal(f.location.label,'Göteborg');assert.equal(f.location.radiusKm,100);assert.equal(f.sort,'distance');assert.deepEqual(f.makes,['BMW']);assert.equal(manualIntent({query:'V70 business nära Göteborg inom 50 km'}).query,'v70 business');});

test('missing publication dates stay unknown through reimport and cannot pass a recent-ad filter',async()=>{const s=await setup([base,{...base,id:'2',publishedAt:new Date().toISOString()}]);assert.equal(s.search({publishedWithinDays:7}).total,1);const unknown=s.rows('SELECT data FROM listings WHERE id=?',['cars:1'])[0];s.importSnapshot(source,{schemaVersion:1,complete:false,listings:[JSON.parse(unknown.data)]});assert.equal(s.search({publishedWithinDays:7}).total,1);s.db.close();});
test('original descriptions exclude navigation and leasing offers are distinguished from cash-sale financing',()=>{const {originalDescription}=require('../electron/blocket.cjs'),{saleIssue}=require('../electron/sale-quality.cjs');const description=originalDescription('<nav>Privatleasing 3095 kr/mån</nav><section><h2>Beskrivning</h2><div>Fin bil.<br>Nyservad.<ul><li>Dragkrok</li></ul><button>Visa mer</button></div></section><footer>Annat innehåll</footer>');assert.match(description,/Fin bil\./);assert.match(description,/Nyservad/);assert.doesNotMatch(description,/Privatleasing|Visa mer|Annat/);assert.equal(saleIssue({...base,description:'Vi erbjuder finansiering och privatleasing från 3095 kr/mån.'}),null);assert.ok(saleIssue({...base,price:3095,description:'BYD privatleasing överlåtes för endast 3 095 kr/mån.'}));assert.equal(saleIssue({...base,price:5000,description:'Reparationsobjekt. Säljs i befintligt skick.'}),null);assert.equal(parseWebListing(html({...schema,offers:{...schema.offers,price:3095},description:'Privatleasing överlåtes för 3 095 kr/mån.'}),'https://dealer.example/car'),null);});
test('one-hop web discovery follows real ItemList ads while ignoring breadcrumbs and object URLs',async()=>{const {listingLinks}=require('../electron/web-listings.cjs');const page=html([{'@type':'BreadcrumbList',itemListElement:[{item:'https://dealer.example/home'},{item:'https://dealer.example/cars'}]},{'@type':'ItemList',itemListElement:[{item:{url:'https://dealer.example/car-1'}},{item:{name:'Ingen URL'}}]}]);assert.deepEqual(listingLinks(page,'https://dealer.example/volvo'),['https://dealer.example/car-1']);const s=await setup([]),reads=[];const discover=new WebListings({store:s,web:{search:async()=>({sources:[{url:'https://dealer.example/volvo'}]})},request:async url=>{reads.push(url);return url.endsWith('/volvo')?page:html({...schema,offers:{...schema.offers,seller:[schema.offers.seller]}});}});const r=await discover.find('Volvo',{maxPrice:60000});assert.equal(r.cars.length,1);assert.equal(r.cars[0].city,'Göteborg');assert.equal(reads.length,2);s.db.close();});
test('handpicked reasons replace unsupported condition claims with grounded facts',async()=>{const s=await setup([base]),a=new CarAgent({store:s,key:()=>null,emit:()=>{}}),cars=s.search().items,chat={id:'reason',cars:[],searchCars:cars,filters:{maxPrice:60000}};await a.execute('select_cars',{selections:[{id:cars[0].id,reason:'Bra skick och nyligen servad.'}]},chat,{signal:new AbortController().signal,emit:()=>{},activity:()=>({}),message:{}});assert.equal(chat.cars[0].selectionReason,'Inom din budget, diesel, automat växellåda.');s.db.close();});
test('batch inspections run concurrently, report individual failures and reject duplicate IDs',async()=>{const s=await setup([base,{...base,id:'2'}]),cars=s.search().items;let active=0,peak=0;const a=new CarAgent({store:s,market:{inspect:async id=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,10));active--;return s.detail(id);}},key:()=>null,emit:()=>{}}),chat={cars:[],searchCars:cars,filters:{}},options={signal:new AbortController().signal,emit:()=>{},activity:()=>({}),message:{}};const r=await a.execute('inspect_car',{ids:cars.map(c=>c.id)},chat,options);assert.equal(r.cars.length,2);assert.equal(peak,2);await assert.rejects(a.execute('inspect_car',{ids:[cars[0].id,cars[0].id]},chat,options));s.db.close();});
test('SQL.js fallback supports the same strict local distance and advanced filters',async()=>{const Module=require('node:module'),load=Module._load;let s;try{Module._load=function(id,...args){if(id==='node:sqlite')throw new Error('Unavailable');return load.call(this,id,...args);};s=await setup([base,{...base,id:'2',city:'Stockholm'}]);}finally{Module._load=load;}assert.equal(s.sqlite,undefined);const r=s.search({location:{label:'Göteborg',radiusKm:50},bodyTypes:['Kombi'],sellerType:'dealer',sort:'distance'});assert.equal(r.total,1);assert.equal(r.items[0].distanceKm,0);s.db.close();});
