const test=require('node:test');const assert=require('node:assert/strict');
const {privateIP}=require('../electron/services.cjs');const {parseCar,fetchCars,buildURL,verifyKnown}=require('../electron/blocket.cjs');const {Store}=require('../electron/core.cjs');
test('public feed refuses internal address classes',()=>{for(const ip of ['127.0.0.1','10.1.2.3','192.168.2.1','172.16.0.2','169.254.0.1','::1','fc00::2','::ffff:127.0.0.1'])assert.ok(privateIP(ip),ip);assert.equal(privateIP('1.1.1.1'),false);});
const doc={id:'123',heading:'BMW 320d',make:'BMW',series:'3-Serie',model:'320d',model_specification:'Touring Steptronic',canonical_url:'https://www.blocket.se/mobility/item/123',year:2017,mileage:14000,mileage_unit:'SCANDINAVIAN_MILE',transmission:'Automatisk',fuel:'Diesel',price:{amount:145000,currency_code:'SEK'},image_urls:[],regno:'ABC123'};
const source={id:'blocket',adapter:'blocket-public',name:'Blocket',enabled:true,mediaAllowed:true,hosts:['www.blocket.se']};
test('Blocket field normalization preserves Swedish mil and actual currencies',()=>{const ad=parseCar(doc);assert.equal(ad.mileage,14000);assert.equal(ad.model,'3-serie');assert.equal(ad.gearbox,'Automat');assert.equal(ad.comparisonVariant,'320d');assert.equal(parseCar({...doc,mileage:140000,mileage_unit:'KILOMETER'}).mileage,14000);assert.equal(parseCar({...doc,mileage:null}),null);assert.equal(parseCar({...doc,model_specification:'Privatleasing 2000kr/mån'}),null);assert.equal(parseCar({...doc,price:{amount:200000,currency_code:'EUR'}}),null);});
test('upstream search uses documented repeated brand parameters and milage_to',()=>{const u=new URL(buildURL({makes:['BMW','Audi'],maxMileage:15000,maxPrice:149999,gearbox:'Automat'},2));assert.deepEqual(u.searchParams.getAll('models'),['BMW','AUDI']);assert.equal(u.searchParams.get('milage_to'),'15000');assert.equal(u.searchParams.get('page'),'2');assert.equal(u.searchParams.get('transmissions'),'AUTOMATIC');});
test('a failed page never imports an incomplete batch or removes existing cars',async()=>{const s=await Store.create();s.setSource(source);let calls=0;await assert.rejects(()=>fetchCars(s,source,{}, {pages:2,request:async()=>{if(++calls===2)throw new Error('HTTP 429');return {docs:[doc],metadata:{result_size:{match_count:100},paging:{last:2}}};}}));assert.equal(s.search().total,0);await fetchCars(s,source,{}, {pages:1,request:async()=>({docs:[doc],metadata:{result_size:{match_count:100}}})});assert.equal(s.search().total,1);await fetchCars(s,source,{maxPrice:100},{pages:1,request:async()=>({docs:[],metadata:{}})});assert.equal(s.search().total,1);});
test('removal verification requires an explicit 404 or 410',async()=>{const s=await Store.create();s.setSource(source);await fetchCars(s,source,{}, {pages:1,request:async()=>({docs:[doc]})});await verifyKnown(s,source,{request:async()=>({})});assert.equal(s.search().total,1);await verifyKnown(s,source,{request:async()=>{throw Object.assign(new Error('error'),{status:500});}});assert.equal(s.search().total,1);await verifyKnown(s,source,{request:async()=>{throw Object.assign(new Error('gone'),{status:410});}});assert.equal(s.search().total,0);});
