import test from 'node:test';import assert from 'node:assert/strict';import worker from '../src/index.js';
const payload={model:'openrouter/free',stream:true,messages:[{role:'user',content:'Hitta en bil'}],tools:[],tool_choice:'auto'};
const env={OPENROUTER_API_KEY:'test-only-key',AI_LIMITER:{limit:async()=>({success:true})}};
const req=data=>new Request('https://carcrow.example/v1/chat/completions',{method:'POST',headers:{'CF-Connecting-IP':'203.0.113.2'},body:JSON.stringify(data)});
test('fixed model fallback order is server-controlled and always has zero price ceilings',async()=>{const previous=globalThis.fetch;let sent;globalThis.fetch=async(_url,options)=>{sent=JSON.parse(options.body);return new Response('data: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}});};try{const settings={...env,MODEL:'nvidia/nemotron-3-super-120b-a12b:free',FALLBACK_MODEL:'nvidia/nemotron-3-ultra-550b-a55b:free'};assert.equal((await worker.fetch(req({...payload,models:['paid/model'],route:'any',reasoning:{effort:'high'}}),settings)).status,200);assert.deepEqual(sent.models,[settings.MODEL,settings.FALLBACK_MODEL]);assert.deepEqual(sent.provider.max_price,{prompt:0,completion:0,request:0});assert.equal(sent.reasoning.effort,'low');await worker.fetch(req({...payload,model:'google/gemma-4-31b-it:free'}),settings);assert.deepEqual(sent.models,['google/gemma-4-31b-it:free']);}finally{globalThis.fetch=previous;}});
test('daily free quota responses stay useful without leaking provider error details',async()=>{const previous=globalThis.fetch;globalThis.fetch=async()=>Response.json({error:{message:'Daily free quota reached',metadata:{raw:'sensitive detail'}}},{status:429});try{const result=await worker.fetch(req(payload),env);assert.equal(result.status,429);const body=await result.text();assert.match(body,/dagliga gratiskvot/);assert.doesNotMatch(body,/sensitive|test-only-key/);}finally{globalThis.fetch=previous;}});
test('paid models, unknown tools and alternate providers never reach OpenRouter',async()=>{let calls=0;const previous=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error('must not run');};try{for(const data of [{...payload,model:'paid/model'},{...payload,tools:[{type:'function',function:{name:'run_code'}}]}])assert.equal((await worker.fetch(req(data),env)).status,400);assert.equal(calls,0);}finally{globalThis.fetch=previous;}});
test('IP limit blocks requests before sending credentials or chats upstream',async()=>{const result=await worker.fetch(req(payload),{...env,AI_LIMITER:{limit:async()=>({success:false})}});assert.equal(result.status,429);assert.equal((await result.text()).includes(env.OPENROUTER_API_KEY),false);});
test('the proxy streams unchanged and forces free-only settings, discarding paid plugins',async()=>{const previous=globalThis.fetch;let received;globalThis.fetch=async(url,options)=>{received={url,options};return new Response('data: {"choices":[]}\n\ndata: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}});};try{const result=await worker.fetch(req({...payload,plugins:[{id:'web'}],max_tokens:999999,provider:{only:['paid']}}),env);assert.equal(result.status,200);const body=JSON.parse(received.options.body);assert.deepEqual(body.models,['nvidia/nemotron-3-super-120b-a12b:free','nvidia/nemotron-3-ultra-550b-a55b:free']);assert.equal(body.model,undefined);assert.equal(body.max_tokens,8192);assert.equal(body.plugins,undefined);assert.deepEqual(body.provider,{max_price:{prompt:0,completion:0,request:0}});assert.equal(received.options.headers.Authorization,'Bearer test-only-key');assert.match(await result.text(),/\[DONE\]/);assert.equal([...result.headers].join('').includes(env.OPENROUTER_API_KEY),false);}finally{globalThis.fetch=previous;}});
test('oversized bodies are rejected and upstream errors never expose their body',async()=>{const big=await worker.fetch(req({...payload,messages:[{role:'user',content:'a'.repeat(600000)}]}),env);assert.equal(big.status,413);const previous=globalThis.fetch;globalThis.fetch=async()=>new Response('sensitive upstream detail',{status:401});try{const failed=await worker.fetch(req(payload),env);assert.equal(failed.status,502);assert.equal((await failed.text()).includes('sensitive'),false);}finally{globalThis.fetch=previous;}});

test('web search forces basic free-quota settings and hides the Tavily key',async()=>{
 const previous=globalThis.fetch,oldCaches=globalThis.caches;const calls=[];
 globalThis.caches={default:{match:async()=>null,put:async()=>{}}};globalThis.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body),headers:options.headers});return Response.json({results:[{title:'Vehicle report',url:'https://www.adac.de/car',content:'Snippet',raw_content:'Real page text'}]});};
 const searchEnv={TAVILY_API_KEY:'private-search-key',SEARCH_LIMITER:{limit:async()=>({success:true})}};
 try{const request=new Request('https://carcrow.example/v1/search',{method:'POST',headers:{'CF-Connecting-IP':'203.0.113.2'},body:JSON.stringify({query:'BMW 125i reliability',search_depth:'advanced',max_results:100})});const result=await worker.fetch(request,searchEnv,{waitUntil:p=>p.catch(()=>{})});assert.equal(result.status,200);const sent=calls[0];assert.equal(calls[1].body.extract_depth,'basic');assert.equal(calls[1].body.urls.length,1);assert.equal(sent.body.search_depth,'basic');assert.equal(sent.body.auto_parameters,false);assert.equal(sent.body.max_results,6);assert.equal(sent.headers.Authorization,'Bearer private-search-key');assert.equal((await result.text()).includes('private-search-key'),false);}finally{globalThis.fetch=previous;globalThis.caches=oldCaches;}
});
test('search quota and unconfigured search stop before upstream calls',async()=>{const request=()=>new Request('https://carcrow.example/v1/search',{method:'POST',headers:{'CF-Connecting-IP':'203.0.113.2'},body:JSON.stringify({query:'car reliability'})});assert.equal((await worker.fetch(request(),{})).status,503);assert.equal((await worker.fetch(request(),{TAVILY_API_KEY:'private-search-key',SEARCH_LIMITER:{limit:async()=>({success:false})}})).status,429);});

test('handpick tool choice is forwarded only for a declared approved tool',async()=>{const previous=globalThis.fetch;let sent;globalThis.fetch=async(_url,options)=>{sent=JSON.parse(options.body);return new Response('data: [DONE]\n\n',{headers:{'Content-Type':'text/event-stream'}});};try{const tools=[{type:'function',function:{name:'select_cars',parameters:{type:'object'}}}];const choice={type:'function',function:{name:'select_cars'}};assert.equal((await worker.fetch(req({...payload,tools,tool_choice:choice}),env)).status,200);assert.deepEqual(sent.tool_choice,choice);assert.equal((await worker.fetch(req({...payload,tools:[],tool_choice:choice}),env)).status,400);assert.equal((await worker.fetch(req({...payload,tools,tool_choice:{type:'function',function:{name:'run_code'}}}),env)).status,400);}finally{globalThis.fetch=previous;}});
test('listing discovery uses the broad search index and separate cache without spending extraction credits',async()=>{const previous=globalThis.fetch,oldCaches=globalThis.caches;const calls=[],keys=[];globalThis.caches={default:{match:async key=>{keys.push(key.url);return null;},put:async()=>{}}};globalThis.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return Response.json({results:[{title:'Volvo V70 till salu',url:'https://dealer.example/car',content:'Verifieras av appen'}]});};const settings={TAVILY_API_KEY:'test-only-key',SEARCH_LIMITER:{limit:async()=>({success:true})}};try{const request=mode=>new Request('https://carcrow.example/v1/search',{method:'POST',headers:{'CF-Connecting-IP':'203.0.113.2'},body:JSON.stringify({query:'Volvo V70',mode})});const ctx={waitUntil:p=>p.catch(()=>{})};assert.equal((await worker.fetch(request('listings'),settings,ctx)).status,200);assert.equal(calls.length,1);assert.equal(calls[0].body.include_domains,undefined);assert.equal(calls[0].body.search_depth,'basic');assert.ok(calls[0].body.exclude_domains.includes('bilweb.se'));assert.equal((await worker.fetch(request('facts'),settings,ctx)).status,200);assert.notEqual(keys[0],keys[1]);assert.equal((await worker.fetch(request('unsafe'),settings,ctx)).status,400);}finally{globalThis.fetch=previous;globalThis.caches=oldCaches;}});

test('approximate location returns only the requesting connection’s town and never its IP',async()=>{const request=new Request('https://carcrow.example/v1/location',{method:'POST'});Object.defineProperty(request,'cf',{value:{country:'SE',city:'Testort',latitude:'57.7',longitude:'11.9',postalCode:'private',region:'private'}});const response=await worker.fetch(request,{},{});assert.equal(response.headers.get('Cache-Control'),'no-store');assert.deepEqual(await response.json(),{label:'Testort',latitude:57.7,longitude:11.9,precision:'network'});assert.equal((await worker.fetch(new Request('https://carcrow.example/v1/location',{method:'POST'}),{},{})).status,404);});
