const fs=require('node:fs'),assert=require('node:assert/strict');
const {Store}=require('../electron/core.cjs'),{Market}=require('../electron/market.cjs'),{SearchSessions}=require('../electron/search-sessions.cjs'),{CarAgent}=require('../electron/agent.cjs'),{WebSearch}=require('../electron/web-search.cjs'),{WebListings}=require('../electron/web-listings.cjs'),{manualIntent}=require('../electron/search-intent.cjs'),{requestJSON}=require('../electron/services.cjs');
(async()=>{
 const output=process.env.CARCROW_LIVE_REPORT||'test-results/live06.json';fs.mkdirSync(require('node:path').dirname(output),{recursive:true});const report={version:'0.6.0',startedAt:new Date().toISOString(),queries:[],web:null,ai:[],status:'running'};
 const store=await Store.create();store.setSource({id:'blocket',name:'Blocket',enabled:true,adapter:'blocket-public',hosts:['www.blocket.se','blocket.se'],mediaAllowed:true});
 const market=new Market(store),sessions=new SearchSessions(store,market);const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));
 try{
  for(const raw of [{query:'V70 business under 60 000 kr'},{makes:['BYD'],maxPrice:300000},{query:'V70',location:{label:'Göteborg',radiusKm:50},sort:'distance'}]){
   const filters=manualIntent(raw),at=performance.now();let first=null;const r=await sessions.start(filters,{onResults:r=>{if(r.items.length&&first===null)first=performance.now()-at;}});assert.ok(r.items.length,'Ingen aktuell träff: '+JSON.stringify(raw));if(filters.maxPrice)assert.ok(r.items.every(c=>c.price<=filters.maxPrice));if(filters.location)assert.ok(r.items.every(c=>c.distanceKm<=50));const sortAt=performance.now();const sorted=sessions.refine(r.sessionId,{...filters,sort:'priceAsc'});report.queries.push({filters,items:r.items.length,total:r.total,firstCardsMs:first,completedMs:performance.now()-at,localSortMs:performance.now()-sortAt,sortedPrice:sorted.items[0]?.price,coverage:r.coverage,examples:r.items.slice(0,3).map(c=>({title:c.title,variant:c.variant,price:c.price,city:c.city,distanceKm:c.distanceKm}))});console.log(JSON.stringify(report.queries.at(-1)));save();
  }
  const web=new WebSearch(),discovery=new WebListings({store,web});const found=await discovery.find('Volvo V70 Business till salu bilhandlare Sverige',{maxPrice:200000});report.web={verified:found.cars.length,cars:found.cars.map(c=>({title:c.title,source:c.source,url:c.url,price:c.price,year:c.year,mileage:c.mileage})),unavailable:found.unavailablePages};save();console.log(JSON.stringify({web:report.web}));assert.ok(found.cars.length,'Inga webbannonser kunde verifieras');
  if(process.argv.includes('--ai')){
   const events=[],calls=[];const {streamCompletion}=require('../electron/stream.cjs');const agent=new CarAgent({store,market,sessions,key:()=>null,emit:e=>events.push(e),stream:async options=>{const started=performance.now();const result=await streamCompletion(options);calls.push({model:result.model,ms:performance.now()-started,tools:result.tool_calls?.map(c=>c.function.name)||[],answer:result.content});save();return result;}});
   let chatId;
   for(const text of ['Hitta en billig pålitlig första bil under 60 000 kr. Handplocka de mest intressanta förslagen.','Sök efter V70 business, fortfarande under 60 000 kr.']){
    const at=performance.now(),chat={id:chatId||require('node:crypto').randomUUID(),title:text,messages:[{role:'user',text}],context:[],cars:[],filters:{}};if(chatId)Object.assign(chat,agent.get(chatId));if(chatId)chat.messages.push({role:'user',text});const message={id:require('node:crypto').randomUUID(),role:'assistant',text:'',activities:[],status:'running'};chat.messages.push(message);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),240000);
    try{await agent.run(chat,message,{text,filters:{},ids:[],runId:'live',signal:controller.signal});}finally{clearTimeout(timer);}chatId=chat.id;const result={text,status:message.status,error:message.error,note:message.note,ms:performance.now()-at,filters:chat.filters,cars:chat.cars.map(c=>({id:c.id,title:c.title,price:c.price,reason:c.selectionReason,webDiscovered:c.webDiscovered})),answer:message.text,calls:[...calls]};report.ai.push(result);save();console.log(JSON.stringify({ai:result}));assert.equal(message.status,'done',message.error);assert.ok(chat.cars.length>1&&chat.cars.length<=12);assert.ok(chat.cars.every(c=>c.price<60000&&c.selectionReason));if(!text.includes('V70'))assert.equal(chat.filters.makes,undefined);else assert.ok(chat.cars.every(c=>c.model.toLowerCase().includes('v70')));assert.doesNotMatch(message.text,/bara en|endast en/i);
   }
  }
  report.status='passed';
 }catch(e){report.status='failed';report.error=e.message;throw e;}finally{report.finishedAt=new Date().toISOString();save();store.db.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
