const fs=require('node:fs'),assert=require('node:assert/strict'),{Store}=require('../electron/core.cjs'),{Market}=require('../electron/market.cjs'),{SearchSessions}=require('../electron/search-sessions.cjs'),{CarAgent}=require('../electron/agent.cjs'),{manualIntent}=require('../electron/search-intent.cjs'),{saleIssue}=require('../electron/sale-quality.cjs');
(async()=>{
 const output=process.env.CARCROW_LIVE_REPORT||'test-results/live07.json';fs.mkdirSync(require('node:path').dirname(output),{recursive:true});const report={version:'0.7.0',startedAt:new Date().toISOString(),queries:[],turns:[],status:'running'},s=await Store.create(),source={id:'blocket',name:'Blocket',adapter:'blocket-public',enabled:true,mediaAllowed:true,hosts:['www.blocket.se','blocket.se']};s.setSource(source);const market=new Market(s),sessions=new SearchSessions(s,market),save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2));
 try{
  for(const text of ['V70 Business under 60 000 kr','Honda Jazz under 60 000 kr','BMW 320d xDrive under 200 000 kr']){const f=manualIntent({query:text}),at=performance.now();let first=null;const r=await sessions.start(f,{onResults:r=>{if(r.items.length&&first===null)first=performance.now()-at;}});assert.ok(r.items.length,text);assert.ok(r.items.every(c=>c.price<=f.maxPrice&&!saleIssue(c)));report.queries.push({text,firstMs:first,completedMs:performance.now()-at,matched:r.total,coverage:r.retrieval,examples:r.items.slice(0,3).map(c=>({title:c.title,price:c.price}))});save();console.log(JSON.stringify(report.queries.at(-1)));}
  if(process.argv.includes('--ai')){
   let end;const a=new CarAgent({store:s,market,sessions,key:()=>null,emit:e=>{if(['done','error','stopped'].includes(e.type))end(e);}});let chatId,shown=[];
   for(const [text,replaceFilters,filters] of [['Hitta en billig pålitlig första bil max 60 000 kr.',false,{}],['Visa andra förslag, undvik bilarna du redan visat.',false,{}],['Hitta alternativ med lägre miltal inom min budget.',false,{}],['Sök igen med dessa filter, behåll övriga önskemål.',true,{maxPrice:60000,models:['Jazz']}],['Vad bör jag kontrollera på den här bilen innan köp?',false,{}]]){
    const at=performance.now(),done=new Promise(r=>end=r),factual=text.startsWith('Vad'),ids=factual?[shown.at(-1)]:[],started=a.start({chatId,text,replaceFilters,filters,ids});chatId=started.chatId;const timer=setTimeout(()=>a.stop(started.runId),180000);let e;try{e=await done;}finally{clearTimeout(timer);}const m=e.chat.messages.at(-1);assert.equal(e.type,'done',m.error);if(!factual){assert.ok(e.chat.cars.length,text);assert.ok(e.chat.cars.every(c=>c.price<=60000&&!saleIssue(c)));if(text.startsWith('Visa'))assert.ok(e.chat.cars.every(c=>!shown.includes(c.id)));if(replaceFilters)assert.ok(e.chat.cars.every(c=>c.model==='Jazz'));shown.push(...e.chat.cars.map(c=>c.id));}else assert.ok(m.sources?.some(s=>s.read),'No read web sources');report.turns.push({text,ms:performance.now()-at,answer:m.text,filters:e.chat.filters,cars:e.chat.cars.map(c=>({title:c.title,year:c.year,mileage:c.mileage,price:c.price,reason:c.selectionReason,description:c.description.slice(0,300)})),sources:m.sources?.map(s=>({title:s.title,read:s.read,url:s.url}))});save();console.log(JSON.stringify({turn:text,ms:performance.now()-at,cars:e.chat.cars.length,answer:m.text}));
   }
  }
  report.status='passed';
 }catch(e){report.status='failed';report.error=e.message;throw e;}finally{report.finishedAt=new Date().toISOString();save();s.db.close();}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
