// Authorized live acceptance with an isolated profile, actual sources and the key-free Worker.
const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{
 const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'carcrow-live-')),output=path.resolve('test-results/live-0.4');fs.mkdirSync(output,{recursive:true});let app,page;
 const report={version:'0.4.0',startedAt:new Date().toISOString(),checks:[],status:'running'};
 const shot=async name=>{await page.waitForTimeout(400);await page.screenshot({path:path.join(output,name)});};
 try{
  app=await electron.launch({...process.env.CARCROW_EXECUTABLE?{executablePath:process.env.CARCROW_EXECUTABLE,args:[]}:{args:['.']},cwd:process.cwd(),env:{...process.env,CARCROW_DATA_DIR:dataDir,CARCROW_TEST_DEMO:''},timeout:90000});page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.getByRole('heading',{name:'Vilken bil spanar du efter?'}).waitFor();const boot=await page.evaluate(()=>window.carcrow.call('bootstrap'));assert.equal(boot.data.stats.aiConfigured,true);assert.equal(boot.data.stats.vehicles,0);assert.ok(!boot.data.sources.some(s=>s.id==='facebook'));await shot('01-welcome.png');
  await page.getByRole('button',{name:'Alla bilar',exact:true}).click();await page.locator('.car-card').first().waitFor({timeout:120000});await page.waitForFunction(()=>!document.querySelector('button[type="submit"]:disabled'),null,{timeout:120000});assert.equal(await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).count(),0);assert.equal(await page.getByText(/\d[\d ]* träffar/).count(),0);await shot('02-market.png');report.checks.push('manual market with current real sources and no AI composer or total');
  await page.getByRole('combobox',{name:'Märke',exact:true}).selectOption('BMW');await page.getByLabel('Modell',{exact:true}).fill('3-serie');await page.getByRole('spinbutton',{name:'Högsta pris'}).fill('200000');await page.getByRole('combobox',{name:'Växellåda',exact:true}).selectOption('Automat');await page.getByRole('button',{name:'Sök bilar',exact:true}).click();await page.locator('.car-card').first().waitFor({timeout:120000});await page.waitForFunction(()=>!document.querySelector('button[type="submit"]:disabled'),null,{timeout:120000});await shot('03-filtered-market.png');
  await page.getByRole('button',{name:'Spara bil',exact:true}).first().click();await page.getByRole('button',{name:'Rekommenderade',exact:true}).click();await page.locator('.recommendation-reason').first().waitFor({timeout:120000});await shot('04-recommended.png');report.checks.push('on-device EmbeddingGemma2 ranks genuine current cars');
  await page.getByRole('button',{name:'Ny chatt',exact:true}).click();await page.evaluate(()=>{window.liveEvents=[];window.carcrow.onAgent(e=>{window.liveEvents.push({type:e.type,model:e.model,label:e.label,delta:e.delta});});});
  await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).fill('Hitta BMW 3-serie under 200 000 kr, automat och max 15 000 mil. Svara kort.');await page.getByRole('button',{name:'Skicka meddelande'}).click();await page.locator('.crow-thinking').waitFor();assert.equal(await page.locator('.live-status,.typing-dots,.stream-cursor').count(),0);assert.equal(await page.locator('.activity-trail').count(),1);await shot('05-thinking.png');
  await page.waitForFunction(()=>window.liveEvents.some(e=>e.type==='text'),null,{timeout:180000});await shot('06-streaming.png');await page.waitForFunction(()=>window.liveEvents.some(e=>['done','error'].includes(e.type)),null,{timeout:240000});
  const id=await page.evaluate(()=>localStorage.getItem('lastChat'));const chat=(await page.evaluate(id=>window.carcrow.call('chat',{id}),id)).data;assert.equal(chat.messages.at(-1).status,'done');assert.ok(chat.cars.length);assert.ok(chat.cars.every(c=>c.make==='BMW'&&c.price<200000&&c.mileage<=15000&&c.gearbox==='Automat'));const events=await page.evaluate(()=>window.liveEvents);report.streamingChunks=events.filter(e=>e.type==='text').length;report.answer=chat.messages.at(-1).text;report.wordCount=report.answer.split(/\s+/).length;assert.ok(report.wordCount<=80,'AI-svaret blev för långt');assert.ok(report.streamingChunks>0);report.sourceStatus=(await page.evaluate(()=>window.carcrow.call('bootstrap'))).data.sources.map(s=>({name:s.name,error:s.error,lastSync:s.lastSync}));await shot('07-answer.png');report.checks.push('real free-only OpenRouter stream, exact database filters and concise answer');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(740,820));await page.getByRole('button',{name:'Visa chatthistorik'}).click();await page.getByRole('dialog').waitFor();await shot('08-history.png');await page.getByRole('button',{name:'Stäng',exact:true}).click();report.checks.push('narrow history opens existing chat');assert.deepEqual(errors,[]);report.status='passed';
 }catch(e){report.status='failed';report.error=e.message;if(page)await shot('failure.png').catch(()=>{});throw e;}
 finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(app){await app.evaluate(({app})=>app.quit()).catch(()=>{});await app.close().catch(()=>{});}fs.rmSync(dataDir,{recursive:true,force:true});}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
