const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {Store}=require('../electron/core.cjs'),{seedDemo}=require('../electron/demo.cjs'),{CarAgent}=require('../electron/agent.cjs');
(async()=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'carcrow-ui07-')),output=process.env.CARCROW_SCREENSHOTS||path.resolve('test-results/ui07');fs.mkdirSync(output,{recursive:true});const report={version:'0.7.0',checks:[],status:'running'};let app,page;
 const check=n=>{report.checks.push(n);console.log(n);};
 try{
  const s=await Store.create(path.join(data,'carcrow.sqlite'));seedDemo(s);const cars=s.search({},true).items.slice(0,4),a=new CarAgent({store:s,demo:()=>true,key:()=>null,emit:()=>{}});a.save({id:'ux07',title:'Mitt testurval',messages:[{id:'u',role:'user',text:'BMW automat max 150000 kr'},{id:'a',role:'assistant',text:'Här är mitt urval.',status:'done'}],context:[],cars,filters:{makes:['BMW'],gearbox:'Automat',maxPrice:150000},userFilters:{}});s.db.close();
  app=await electron.launch({...process.env.CARCROW_EXECUTABLE?{executablePath:process.env.CARCROW_EXECUTABLE,args:[]}:{args:['.']},cwd:process.cwd(),env:{...process.env,CARCROW_DATA_DIR:data,CARCROW_TEST_DEMO:'1'},timeout:90000});page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Vilken bil spanar du efter?'}).waitFor();await page.getByRole('button',{name:'Mitt testurval',exact:true}).click();await page.locator('.car-card').first().waitFor();
  const ids=await page.locator('.car-card').evaluateAll(es=>es.map(e=>e.getAttribute('data-id')||e.textContent));await page.getByRole('combobox',{name:'Sortera annonser'}).selectOption('mileage');const sorted=await page.locator('.car-card').evaluateAll(es=>es.map(e=>e.getAttribute('data-id')||e.textContent));assert.deepEqual([...ids].sort(),[...sorted].sort());assert.equal((await page.evaluate(()=>window.carcrow.call('chat',{id:'ux07'}))).data.cars.length,4);check('sorting a shortlist preserves its exact cars and persisted chat');
  await page.locator('.car-card').first().getByRole('button',{name:/Visa /}).click();await page.getByRole('button',{name:'Fråga CarCrow om bilen'}).click();await page.locator('.composer-context').waitFor();assert.match(await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).inputValue(),/Vad bör jag kontrollera/);check('car questions carry a visible selected car into the composer');
  await page.locator('.car-card').first().getByRole('button',{name:/Visa /}).click();await page.getByRole('button',{name:'Hitta liknande bilar'}).click();assert.match(await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).inputValue(),/Hitta fler bilar som liknar/);check('similar-car action prepares a contextual search');
  await page.getByRole('button',{name:'Ta bort filtret BMW'}).click();await page.locator('.message-error').waitFor();const replaced=(await page.evaluate(()=>window.carcrow.call('chat',{id:'ux07'}))).data;assert.equal(replaced.filters.makes,undefined);assert.equal(replaced.filters.gearbox,'Automat');assert.equal(replaced.filters.maxPrice,150000);assert.ok(replaced.intentStart>0);check('removing a filter reaches the backend and prevents old chat requirements returning');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1400,900));await page.screenshot({path:path.join(output,'01-wide.png')});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(740,820));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'02-narrow.png')});check('new actions and filter chips fit wide and narrow layouts');assert.deepEqual(errors,[]);report.status='passed';
 }catch(e){report.status='failed';report.error=e.message;if(page)await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});throw e;}
 finally{fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));if(app){await app.evaluate(({app})=>app.quit()).catch(()=>{});await app.close().catch(()=>{});}fs.rmSync(data,{recursive:true,force:true});}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
