const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{
 const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'carcrow-ui-')),output=process.env.CARCROW_SCREENSHOTS||path.resolve('test-results');fs.mkdirSync(output,{recursive:true});
 const report={startedAt:new Date().toISOString(),platform:process.platform,hostArchitecture:process.arch,packaged:!!process.env.CARCROW_EXECUTABLE,checks:[],aiConfiguration:'pending',status:'running'};let app,page;const failures=[];
 const check=name=>{report.checks.push(name);console.log(name);};
 try{
  app=await electron.launch({...process.env.CARCROW_EXECUTABLE?{executablePath:process.env.CARCROW_EXECUTABLE,args:[]}:{args:['.']},cwd:process.cwd(),env:{...process.env,CARCROW_DATA_DIR:dataDir,CARCROW_TEST_DEMO:'1'},timeout:90000});page=await app.firstWindow();page.on('pageerror',e=>failures.push(e.message));
  report.version=await app.evaluate(({app})=>app.getVersion());report.applicationArchitecture=await app.evaluate(()=>process.arch);
  await page.getByRole('heading',{name:'Vilken bil letar du efter?'}).waitFor();await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).waitFor();await page.screenshot({path:path.join(output,'01-chat.png')});
  const bootstrap=await page.evaluate(()=>window.carcrow.call('bootstrap'));assert.equal(bootstrap.data.stats.model,'openrouter/free');assert.equal(bootstrap.data.stats.vehicles,24);check('chat-first launch and free-only model');
  await page.getByRole('button',{name:'Alla bilar',exact:true}).click();await page.locator('.car-card').first().waitFor();assert.ok(await page.locator('.car-card').count()<24);check('virtualized real database results');
  await page.getByRole('button',{name:'Spara bil',exact:true}).first().click();await page.getByRole('button',{name:'Sparade',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.car-card').length===1);check('bookmarks');
  await page.getByRole('button',{name:'Alla bilar',exact:true}).click();await page.getByRole('button',{name:'Filter',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Hitta din bil'});await dialog.getByLabel('BMW',{exact:true}).check();await dialog.locator('input[type="number"]').nth(1).fill('150000');await dialog.getByRole('button',{name:'Visa bilar',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.car-card').length===1);
  await page.getByRole('button',{name:'Visa BMW 3-serie 320d',exact:true}).click();await page.getByRole('dialog').waitFor();assert.match(await page.getByRole('dialog').innerText(),/22,2 %/);assert.match(await page.getByRole('dialog').innerText(),/Demoflöde B/);await page.screenshot({path:path.join(output,'02-details.png')});await page.getByRole('button',{name:'Stäng',exact:true}).click();check('filters, details, duplicate offers and computed median');
  await page.getByRole('button',{name:'Bevaka sökning',exact:true}).click();await page.getByRole('dialog',{name:'Bevaka sökning'}).getByLabel('Namn').fill('Min BMW');await page.getByRole('button',{name:'Spara bevakning',exact:true}).click();
  await page.getByRole('button',{name:'Inställningar',exact:true}).click();await page.getByRole('button',{name:/Bevakningar/}).click();assert.match(await page.locator('.settings-content').innerText(),/Min BMW/);check('saved searches');
  await page.getByRole('button',{name:'Alla bilar',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.results-header')?.innerText.includes('24 träffar'));await page.getByRole('combobox',{name:'Sortera annonser'}).selectOption('deals');await page.waitForFunction(()=>document.querySelectorAll('.deal-badge').length===4);
  await page.getByRole('button',{name:'Välj för jämförelse BMW 3-serie 320d',exact:true}).first().click();await page.getByRole('button',{name:'Välj för jämförelse Audi A4 2.0 TDI',exact:true}).first().click();await page.locator('.selection-bar').getByRole('button',{name:'Jämför',exact:true}).click();await page.getByRole('dialog',{name:'Jämför dina val'}).waitFor();assert.equal(await page.locator('.compare-table thead th').count(),3);await page.screenshot({path:path.join(output,'03-compare.png')});await page.getByRole('button',{name:'Stäng',exact:true}).click();check('database-backed deals and comparison');
  await page.getByRole('button',{name:'Inställningar',exact:true}).click();await page.getByRole('heading',{name:'AI',exact:true}).waitFor();assert.equal(await page.locator('input[type="password"]').count(),0);assert.equal(await page.getByLabel('API-nyckel',{exact:true}).count(),0);await page.screenshot({path:path.join(output,'04-settings.png')});
  for(const payload of [{key:'test-only-nonfunctional-key'},{key:''},{model:'paid-model'}]){
   const reply=await page.evaluate(p=>window.carcrow.call('settings',p),payload);assert.equal(reply.ok,false);assert.match(reply.error,/konfiguration är låst/);
  }
  const retired=await page.evaluate(()=>window.carcrow.call('testKey'));assert.equal(retired.ok,false);
  const b=await page.evaluate(()=>window.carcrow.call('bootstrap'));assert.equal(b.data.stats.aiConfigured,false);assert.equal(b.data.stats.model,'openrouter/free');assert.equal(JSON.stringify(b).includes('test-only-nonfunctional-key'),false);assert.equal(fs.readFileSync(path.join(dataDir,'carcrow.sqlite')).includes(Buffer.from('test-only-nonfunctional-key')),false);report.aiConfiguration='locked';check('immutable private AI configuration and free-only enforcement');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(740,820));await page.getByRole('button',{name:'Chat',exact:true}).click();await page.getByRole('heading',{name:'Vilken bil letar du efter?'}).waitFor();await page.screenshot({path:path.join(output,'05-narrow.png')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('narrow layout');
  await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).fill('Testa en BMW');await page.getByRole('button',{name:'Skicka meddelande'}).click();await page.locator('.message-error').waitFor();assert.match(await page.locator('.message-error').innerText(),/OpenRouter är inte konfigurerat/);check('agent errors recover visibly');
  assert.deepEqual(failures,[]);report.status='passed';
 }catch(e){report.status='failed';report.error=e.message;if(page)await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});throw e;}
 finally{report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));if(app){await app.evaluate(({app})=>app.quit()).catch(()=>{});await app.close().catch(()=>{});}fs.rmSync(dataDir,{recursive:true,force:true});}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
