const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'carcrow-ui06-')),output=process.env.CARCROW_SCREENSHOTS||path.resolve('test-results/ui06');fs.mkdirSync(output,{recursive:true});const report={version:'0.6.0',checks:[],status:'running'};let app,page;
 const check=n=>{report.checks.push(n);console.log(n);};
 try{
  app=await electron.launch({...process.env.CARCROW_EXECUTABLE?{executablePath:process.env.CARCROW_EXECUTABLE,args:[]}:{args:['.']},cwd:process.cwd(),env:{...process.env,CARCROW_DATA_DIR:data,CARCROW_TEST_DEMO:'1'},timeout:90000});page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'Vilken bil spanar du efter?'}).waitFor();
  const denied=await page.evaluate(()=>window.carcrow.call('approximateLocation'));assert.equal(denied.ok,false);assert.match(denied.error,/Aktivera/);const initial=await page.evaluate(()=>window.carcrow.call('bootstrap'));assert.equal(initial.data.locationConsent,false);assert.equal(initial.data.sources.some(s=>s.id==='bilweb'),false);check('location stays off before explicit consent and Bilweb is absent');
  await page.getByRole('button',{name:'Alla bilar',exact:true}).click();await page.locator('.car-card').first().waitFor();await page.getByRole('button',{name:'Filter',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Anpassa din sökning'});await dialog.getByRole('textbox',{name:'Märken',exact:true}).fill('Mitt specialmärke');await dialog.getByRole('button',{name:'Använd ”Mitt specialmärke”'}).click();await dialog.getByRole('button',{name:'Ta bort Mitt specialmärke'}).waitFor();await dialog.getByRole('button',{name:'Ta bort Mitt specialmärke'}).click();await page.screenshot({path:path.join(output,'07-filter-car.png')});check('searchable brand choices accept and remove an unknown brand');
  await dialog.getByRole('tab',{name:'Plats',exact:true}).click();await dialog.getByRole('textbox',{name:'Sök ort'}).fill('Göteborg');await dialog.locator('.choice-options button').first().waitFor();await dialog.locator('.choice-options button').first().click();await dialog.getByRole('combobox',{name:'Sökavstånd'}).selectOption('100');await dialog.getByLabel('Närmaste bilar först').check();await page.screenshot({path:path.join(output,'08-filter-location.png')});check('town and radius can be selected without sharing device or network position');
  await dialog.getByRole('tab',{name:'Fler val',exact:true}).click();await dialog.getByRole('textbox',{name:'Kaross',exact:true}).fill('Kombi');await dialog.getByRole('button',{name:'Kombi',exact:true}).click();await dialog.getByRole('textbox',{name:'Bränsle',exact:true}).fill('Bensin');await dialog.getByRole('button',{name:'Bensin',exact:true}).click();await page.screenshot({path:path.join(output,'09-filter-more.png')});check('advanced groups mount separately and show selected fuel and body chips');
  await dialog.getByRole('button',{name:'Återställ',exact:true}).click();await dialog.getByRole('tab',{name:'Bilen',exact:true}).click();await dialog.getByLabel('Från',{exact:true}).first().fill('100000');await dialog.getByLabel('Till',{exact:true}).first().fill('50000');await dialog.getByRole('button',{name:'Visa bilar',exact:true}).click();await dialog.getByRole('alert').waitFor();assert.match(await dialog.getByRole('alert').innerText(),/Från-värdet/);await dialog.getByRole('button',{name:'Återställ',exact:true}).click();await dialog.getByRole('button',{name:'Visa bilar',exact:true}).click();await dialog.waitFor({state:'detached'});check('invalid bounds remain reviewable inside the filter dialog');
  for(const [tail,city] of [['Jag vill ha en bensinbil med dragkrok nära Göteborg','Göteborg'],['Jag söker en elbil i Umeå','Umeå']]){await page.getByRole('button',{name:'Ny chatt',exact:true}).click();const text='Jag fortsätter min tidigare långa och detaljerade bilsökning. '+tail;await page.getByRole('textbox',{name:'Meddelande till CarCrow'}).fill(text);await page.getByRole('button',{name:'Skicka meddelande'}).click();await page.locator('.message-error').waitFor();assert.ok(city);}
  if(!await page.getByRole('textbox',{name:'Sök chattar',exact:true}).isVisible())await page.getByRole('button',{name:'Visa chatthistorik'}).click();const search=page.locator('input[aria-label="Sök chattar"]:visible');await search.fill('goteborg');await page.waitForFunction(()=>document.querySelectorAll('.history-item').length===1);const matches=await page.evaluate(()=>window.carcrow.call('chats',{query:'goteborg'}));assert.equal(matches.data.length,1);assert.equal(matches.data[0].title.includes('Göteborg'),false);await page.screenshot({path:path.join(output,'10-chat-search.png')});check('chat search finds message content beyond the truncated title with accent folding');
  await search.fill('definitivt-inte-en-chatt');await page.waitForFunction(()=>document.querySelectorAll('.history-item').length===0);await page.getByText('Inga chattar matchar.',{exact:true}).filter({visible:true}).waitFor();await page.getByRole('button',{name:'Rensa chattsökning'}).click();await page.waitForFunction(()=>document.querySelectorAll('.history-item').length===2);check('chat search empty state and clear restore the history');
  const historyDialog=page.getByRole('dialog',{name:'Dina chattar',exact:true});if(await historyDialog.isVisible()){await historyDialog.getByRole('button',{name:'Stäng'}).click();await historyDialog.waitFor({state:'detached'});}await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(900,760));await page.getByRole('button',{name:'Visa chatthistorik'}).click();await historyDialog.getByRole('textbox',{name:'Sök chattar'}).fill('inte-en-chatt');await historyDialog.getByText('Inga chattar matchar.',{exact:true}).waitFor();await historyDialog.getByRole('button',{name:'Rensa chattsökning'}).click();await historyDialog.getByRole('textbox',{name:'Sök chattar'}).fill('umea');await page.waitForFunction(()=>document.querySelectorAll('.history-dialog > button').length===1);await page.screenshot({path:path.join(output,'11-chat-search-narrow.png')});check('narrow chat search supports matching, empty state and clearing');
  assert.deepEqual(errors,[]);report.status='passed';
 }catch(e){report.status='failed';report.error=e.message;if(page)await page.screenshot({path:path.join(output,'06-failure.png')}).catch(()=>{});throw e;}finally{fs.writeFileSync(path.join(output,'report06.json'),JSON.stringify(report,null,2));if(app){await app.evaluate(({app})=>app.quit()).catch(()=>{});await app.close().catch(()=>{});}fs.rmSync(data,{recursive:true,force:true});}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
