import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {useVirtualizer} from '@tanstack/react-virtual';
import {ArrowUp,ArrowUpRight,Bookmark,CarFront,Check,ChevronDown,ChevronRight,LoaderCircle,MessageSquare,Plus,Settings,SlidersHorizontal,Square,Trash2,X,RefreshCw,Bell,AlertCircle} from 'lucide-react';
import {call,type Bootstrap,type Car,type Filters,type SearchResult,type Chat,type Message,type Activity,type AgentEvent,number,filterText,relative} from './types';
import {CarCard,Details,Modal} from './components';
import {FilterPanel,Compare} from './panels';

type View='chat'|'market'|'saved'|'settings'|'watches';
type Results=SearchResult&{hasMore?:boolean;comparison?:boolean};
type ChatSummary={id:string;title:string;updated:string};
const emptyResults:Results={items:[],total:0,page:0,filters:{sort:'newest'},hasMore:true,remaining:0};
export function Crow({size=28}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M7 22c-2-4-1-10 3-14 3-3 8-3 11 0l6 2-5 4c0 7-5 12-12 11l-6 3 3-6Z" fill="currentColor"/><path d="m10 15 8 2-8 5" stroke="var(--crow-wing,#fff)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/><circle cx="19" cy="9.6" r="1.1" fill="var(--crow-wing,#fff)"/></svg>;}

export default function App(){
  const [boot,setBoot]=useState<Bootstrap|null>(null),[view,setView]=useState<View>('chat'),[chats,setChats]=useState<ChatSummary[]>([]),[chat,setChat]=useState<Chat|null>(null);
  const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[runId,setRunId]=useState(''),[phase,setPhase]=useState(''),[result,setResult]=useState<Results>(emptyResults),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [detail,setDetail]=useState<Car|null>(null),[selected,setSelected]=useState<Car[]>([]),[filterOpen,setFilterOpen]=useState(false),[compareOpen,setCompareOpen]=useState(false),[watchOpen,setWatchOpen]=useState(false),[showCars,setShowCars]=useState(false);
  const current=useRef({chatId:'',busy:false,view,result});current.current={chatId:chat?.id||'',busy,view,result};
  const sending=useRef(false),cancelPending=useRef(false),composer=useRef<HTMLTextAreaElement>(null),chatScroll=useRef<HTMLDivElement>(null),followBottom=useRef(true),loadEpoch=useRef(0),resultFetch=useRef(false);
  const refresh=useCallback(async()=>{try{const [b,c]=await Promise.all([call<Bootstrap>('bootstrap'),call<ChatSummary[]>('chats')]);setBoot(b);setChats(c);}catch(e){setError((e as Error).message);}},[]);
  useEffect(()=>{refresh();const last=localStorage.getItem('lastChat');if(last)openChat(last);return window.carcrow?.onChanged(()=>{refresh();});},[refresh]);
  useEffect(()=>window.carcrow?.onAgent((e:AgentEvent)=>{
    if(e.chatId!==current.current.chatId)return;
    if(e.runId)setRunId(e.runId);
    if(e.type==='phase'){setPhase(e.label||'CarCrow arbetar');return;}
    if(e.type==='results'&&e.result){if(current.current.view==='chat'){setResult(e.result);}setChat(c=>c?{...c,cars:e.result!.items,filters:e.result!.filters||{},total:e.result!.total,remaining:e.result!.remaining,comparison:e.result!.comparison,hasMore:e.result!.hasMore}:c);return;}
    if(['done','error','stopped'].includes(e.type)){setBusy(false);sending.current=false;setRunId('');setPhase('');if(e.chat)setChat(e.chat);refresh();return;}
    if(e.type==='text'||e.type==='replaceText'||e.type==='activity'||e.type==='source')setChat(c=>{
      if(!c)return c;const messages=[...c.messages];let at=messages.findIndex(m=>m.id===e.messageId);if(at<0){for(let i=messages.length-1;i>=0;i--)if(messages[i].role==='assistant'&&messages[i].status==='running'){at=i;break;}}if(at<0)return c;
      const m={...messages[at],id:e.messageId};
      if(e.type==='text')m.text+=e.delta||'';else if(e.type==='replaceText')m.text=e.text||'';
      else {const a=e.type==='source'?{id:'source:'+e.source,label:e.label||e.source||'',status:e.status||'running'} as Activity:e.activity;if(a){const activities=[...(m.activities||[])];const index=activities.findIndex(x=>x.id===a.id);if(index<0)activities.push(a);else activities[index]=a;m.activities=activities;}}
      messages[at]=m;return {...c,messages};
    });
    if(e.type==='source'&&e.status==='running')setPhase(e.label||'Hämtar annonser');
  }),[refresh]);
  useEffect(()=>{if(followBottom.current)chatScroll.current?.scrollTo({top:chatScroll.current.scrollHeight,behavior:'instant'});},[chat?.messages,phase]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setView('chat');composer.current?.focus();}if((e.metaKey||e.ctrlKey)&&e.key===','){e.preventDefault();setView('settings');}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
  useEffect(()=>{if(composer.current){composer.current.style.height='auto';composer.current.style.height=Math.min(180,composer.current.scrollHeight)+'px';}},[input,view,chat?.id]);

  async function send(text=input){
    if(sending.current||busy||!text.trim())return;sending.current=true;cancelPending.current=false;setBusy(true);setError('');setView('chat');setShowCars(false);setInput('');setPhase('CarCrow planerar sökningen');followBottom.current=true;
    const next=chat||{id:crypto.randomUUID(),title:text.trim().slice(0,60),messages:[],cars:[],filters:{},hasMore:true};
    localStorage.setItem('lastChat',next.id);current.current.chatId=next.id;setChat({...next,messages:[...next.messages,{id:crypto.randomUUID(),role:'user',text:text.trim()},{id:'pending:'+crypto.randomUUID(),role:'assistant',text:'',status:'running',startedAt:new Date().toISOString(),activities:[]}]});
    try{const started=await call<{chatId:string;runId:string}>('agentStart',{chatId:next.id,text,filters:result.filters||next.filters,ids:selected.map(c=>c.id)});setRunId(started.runId);if(cancelPending.current)await call('agentStop',{runId:started.runId});}
    catch(e){sending.current=false;setBusy(false);setPhase('');setChat(c=>c?{...c,messages:c.messages.map(m=>m.status==='running'?{...m,status:'error',error:(e as Error).message}:m)}:c);}
  }
  async function stop(){cancelPending.current=true;if(runId)await call('agentStop',{runId});setPhase('Avbryter sökningen');}
  function newChat(){if(busy)return;localStorage.removeItem('lastChat');++loadEpoch.current;setChat(null);setResult(emptyResults);setSelected([]);setView('chat');setInput('');setShowCars(false);setError('');followBottom.current=true;setTimeout(()=>composer.current?.focus(),20);}
  async function openChat(id:string){if(busy)return;try{const c=await call<Chat>('chat',{id});if(!c)return;localStorage.setItem('lastChat',id);++loadEpoch.current;setChat(c);setView('chat');setResult(chatResults(c));setShowCars(false);followBottom.current=true;}catch(e){setError((e as Error).message);}}
  async function openCar(id:string){try{setDetail(await call<Car>('detail',{id}));}catch(e){setError((e as Error).message);}}
  async function bookmark(id:string){try{const saved=await call<boolean>('bookmark',{id});setResult(r=>({...r,items:r.items.map(c=>c.id===id?{...c,saved}:c)}));if(detail?.id===id)setDetail({...detail,saved});setSelected(s=>s.map(c=>c.id===id?{...c,saved}:c));}catch(e){setError((e as Error).message);}}
  const toggleSelect=(car:Car)=>setSelected(s=>s.some(c=>c.id===car.id)?s.filter(c=>c.id!==car.id):s.length<4?[...s,car]:s);
  async function loadBase(f:Filters,saved=false){const epoch=++loadEpoch.current;setLoading(true);setError('');setResult({items:[],total:0,page:0,filters:f,remaining:0,hasMore:false});try{let r:Results={...await call<SearchResult>('searchNext',{filters:f,saved,hasMore:!saved&&!boot?.demo}),filters:f};if(epoch!==loadEpoch.current)return;setResult(r);if(view==='chat')setChat(c=>c?{...c,cars:r.items,filters:f,total:r.total,remaining:r.remaining,hasMore:r.hasMore}:c);if(!r.items.length&&!saved&&!boot?.demo){r=await call<Results>('marketNext',{filters:f});if(epoch===loadEpoch.current)setResult(r);}}catch(e){setError((e as Error).message);}finally{if(epoch===loadEpoch.current)setLoading(false);}}
  async function navigate(next:View){++loadEpoch.current;setError('');if(next==='chat'){setView(next);setResult(chat?chatResults(chat):emptyResults);return;}setView(next);setSelected([]);if(next==='market'||next==='saved')await loadBase({sort:'newest'},next==='saved');}
  async function more(){
    if(resultFetch.current||loading||busy)return;resultFetch.current=true;setLoading(true);const snapshot=current.current.result;const epoch=loadEpoch.current;const f=snapshot.filters||{};
    try{
      let next:Results;
      if((snapshot.remaining??Math.max(0,snapshot.total-snapshot.items.length))>0)next=await call<Results>('searchNext',{filters:f,saved:view==='saved',excludeIds:snapshot.items.map(c=>c.id),hasMore:snapshot.hasMore});
      else if(snapshot.hasMore&&view!=='saved')next=await call<Results>('marketNext',{filters:f,excludeIds:snapshot.items.map(c=>c.id)});
      else return;
      if(epoch!==loadEpoch.current)return;
      setResult(r=>{const items=new Map(r.items.map(c=>[c.id,c]));for(const c of next.items)items.set(c.id,c);const updated={...next,items:[...items.values()]};if(current.current.view==='chat')setChat(c=>c?{...c,cars:updated.items,total:updated.total,remaining:updated.remaining,hasMore:updated.hasMore}:c);return updated;});
    }catch(e){setError((e as Error).message);}finally{resultFetch.current=false;setLoading(false);}
  }
  const composerUI=<form className={'composer '+(busy?'working':'')} onSubmit={(e:FormEvent)=>{e.preventDefault();send();}}><textarea ref={composer} aria-label="Meddelande till CarCrow" rows={1} value={input} onChange={e=>setInput(e.target.value)} placeholder={chat?'Fortsätt sökningen…':'Beskriv bilen du vill hitta…'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/>{busy?<button type="button" className="send" aria-label="Stoppa sökningen" title="Stoppa sökningen" onClick={stop}><Square size={17} fill="currentColor"/></button>:<button className="send" aria-label="Skicka meddelande" disabled={!input.trim()}><ArrowUp size={21}/></button>}</form>;
  if(!boot)return <div className="startup"><Crow size={46}/><h1>CarCrow</h1>{error?<><p>{error}</p><button onClick={refresh}>Försök igen</button></>:<LoaderCircle className="spin"/>}</div>;
  const hasResults=!!result.items.length||busy&&showCars;
  const resultsPanel=<section className={'results-panel '+(view==='chat'?'chat-results':'')} aria-label="Sökresultat"><header className="results-header"><div><h2>{view==='saved'?'Sparade bilar':'Bilar'}</h2><span title="Matchande bilar som faktiskt hämtats till databasen">{number(result.total)} träffar</span></div><div><button className="icon-button" aria-label="Filter" title="Filter" onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={19}/></button><select aria-label="Sortera annonser" value={result.filters?.sort||'newest'} onChange={e=>loadBase({...result.filters,sort:e.target.value},view==='saved')}><option value="newest">Senaste</option><option value="priceAsc">Lägst pris</option><option value="priceDesc">Högst pris</option><option value="mileage">Lägst miltal</option><option value="deals">Fynd</option></select><button className="icon-button" aria-label="Bevaka sökning" title="Bevaka sökning" onClick={()=>setWatchOpen(true)}><Bell size={18}/></button></div></header>{filterText(result.filters||{})!=='Alla bilar'&&<button className="criteria" onClick={()=>setFilterOpen(true)}>{filterText(result.filters||{})}<ChevronDown size={15}/></button>}
    <CarGrid items={result.items} loading={loading} more={more} canLoad={!error&&!busy&&(!!result.hasMore||(result.remaining??Math.max(0,result.total-result.items.length))>0)} selected={selected} open={openCar} save={bookmark} select={toggleSelect}/>
    {(error||result.sourceWarning)&&<div className="results-error" role="alert"><span>{error||result.sourceWarning}</span><button onClick={()=>{setError('');current.current.result={...current.current.result,hasMore:true,sourceWarning:null};setResult(r=>({...r,hasMore:true,sourceWarning:null}));more();}}>Försök igen</button></div>}
    {!!selected.length&&<div className="selection-bar"><strong>{selected.length} valda</strong><button onClick={async()=>{try{setSelected(await Promise.all(selected.map(c=>call<Car>('detail',{id:c.id}))));setCompareOpen(true);}catch(e){setError((e as Error).message);}}}>Jämför<ArrowUpRight size={16}/></button><button className="icon-button" aria-label="Rensa valda bilar" onClick={()=>setSelected([])}><X size={16}/></button></div>}
  </section>;
  return <div className="app-shell"><aside className="sidebar"><div className="window-drag"/><button className="brand" aria-label="CarCrow" onClick={newChat}><Crow size={31}/><strong>CarCrow</strong></button><button className="new-chat" onClick={newChat} disabled={busy}><Plus size={18}/><span>Ny chat</span></button><nav aria-label="Huvudnavigation">{([{id:'chat',label:'Chat',icon:MessageSquare},{id:'market',label:'Alla bilar',icon:CarFront},{id:'saved',label:'Sparade',icon:Bookmark}] as const).map(({id,label,icon:Icon})=><button key={id} aria-label={label} title={label} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon size={18}/><span>{label}</span>{id==='chat'&&busy&&<LoaderCircle className="spin" size={14}/>}</button>)}</nav><div className="chat-history">{chats.map(c=><div className={'history-item '+(chat?.id===c.id?'active':'')} key={c.id}><button onClick={()=>openChat(c.id)} disabled={busy} title={c.title}>{c.title}</button><button className="delete-chat" disabled={busy} aria-label={'Ta bort chatten '+c.title} onClick={async()=>{await call('chatDelete',{id:c.id});if(chat?.id===c.id)newChat();refresh();}}><Trash2 size={13}/></button></div>)}</div><button className={'settings-nav '+(view==='settings'?'active':'')} aria-label="Inställningar" title="Inställningar" onClick={()=>navigate('settings')}><Settings size={18}/><span>Inställningar</span></button></aside>
    <main className="workspace"><header className="window-bar"><span>{view==='chat'?(chat?.title||'Ny chat'):({market:'Alla bilar',saved:'Sparade',settings:'Inställningar',watches:'Bevakningar'} as const)[view]}</span>{boot.demo&&<span className="demo-label">Exempelbilar</span>}{view==='chat'&&hasResults&&<div className="mobile-switch"><button className={!showCars?'active':''} onClick={()=>setShowCars(false)}>Chat</button><button className={showCars?'active':''} onClick={()=>setShowCars(true)}>Bilar {result.items.length}</button></div>}</header>
    {view==='chat'?<div className={'chat-workspace '+(hasResults?'with-results':'')+' '+(showCars?'cars-visible':'chat-visible')}><section className="chat-panel"><div className={'chat-scroll '+(!chat?.messages.length?'empty-chat':'')} ref={chatScroll} onScroll={()=>{const el=chatScroll.current;if(el)followBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<100;}}>
      {!chat?.messages.length?<div className="welcome"><Crow size={52}/><h1>Vilken bil letar du efter?</h1>{composerUI}<div className="starters">{['BMW eller Audi under 150 000 kr','En bra familjebil','Hitta intressanta fynd'].map(text=><button key={text} onClick={()=>send(text)}>{text}<ArrowUpRight size={14}/></button>)}</div></div>:<div className="messages" role="log" aria-label="Chat med CarCrow">{chat.messages.map(m=><ChatMessage key={m.id} message={m} phase={phase} retry={()=>{const user=[...chat.messages].reverse().find(x=>x.role==='user');if(user)send(user.text);}}/>)}</div>}
    </div>{!!chat?.messages.length&&<div className="composer-dock">{busy&&<div className="live-status" role="status"><LoaderCircle size={15} className="spin"/><span>{phase||'CarCrow arbetar'}</span></div>}{composerUI}</div>}</section>{hasResults&&resultsPanel}</div>:view==='market'||view==='saved'?<div className="market-workspace">{resultsPanel}</div>:view==='settings'?<SettingsView boot={boot} failure={error} refresh={refresh} error={message=>setError(message)} watches={()=>setView('watches')}/>:<div className="settings-content"><h1>Bevakningar</h1>{boot.watches.map(w=><div className="setting-row" key={w.id}><div><strong>{w.name}</strong><span>{number(w.total)} träffar{w.newCount?' · '+w.newCount+' nya':''}</span></div><button onClick={()=>{setView('market');loadBase(w.filters);call('markWatch',{id:w.id});}}>Visa bilar<ChevronRight size={17}/></button><button className="icon-button" aria-label={'Ta bort '+w.name} onClick={async()=>{await call('unwatch',{id:w.id});refresh();}}><Trash2 size={17}/></button></div>)}{!boot.watches.length&&<p>Inga sparade sökningar ännu.</p>}</div>}
    </main>{filterOpen&&<FilterPanel boot={boot} filters={result.filters||{}} close={()=>setFilterOpen(false)} apply={f=>{setFilterOpen(false);loadBase(f,view==='saved');}}/>}{detail&&<Details car={detail} close={()=>setDetail(null)} save={()=>bookmark(detail.id)} openOffer={async offerId=>{try{await call('openOffer',{id:detail.id,offerId});}catch(e){setError((e as Error).message);}}} openPeer={openCar}/>}{compareOpen&&<Compare cars={selected} close={()=>setCompareOpen(false)} open={id=>{setCompareOpen(false);openCar(id);}}/>}{watchOpen&&<WatchDialog filters={result.filters||{}} close={()=>setWatchOpen(false)} saved={()=>{setWatchOpen(false);refresh();}}/>}
  </div>;
}

function chatResults(c:Chat):Results{return {items:c.cars,total:c.total??c.cars.length,page:0,filters:c.filters,remaining:c.remaining??0,hasMore:c.hasMore,comparison:c.comparison};}
function ChatMessage({message,phase,retry}:{message:Message;phase:string;retry:()=>void}){
  const activities=message.activities||[],working=message.status==='running';
  return <article className={'message '+message.role}>{message.role==='assistant'&&<div className="assistant-avatar"><Crow size={24}/></div>}<div className="message-body">{message.role==='assistant'&&(activities.length>0||working)&&<details className="activity-trail"><summary>{working?<LoaderCircle size={14} className="spin"/>:message.status==='error'?<AlertCircle size={14}/>:message.status==='stopped'?<Square size={13}/>:<Check size={14}/>}<span>{working?(phase||activities.at(-1)?.label||'CarCrow arbetar'):message.status==='stopped'?'Sökningen avbröts':message.status==='error'?'Sökningen misslyckades':activities.length?'Visa sökningen':'Färdigt'}</span><ChevronDown size={14}/></summary><ol>{activities.map(a=><li key={a.id}>{a.status==='running'?<LoaderCircle size={13} className="spin"/>:a.status==='done'?<Check size={13}/>:a.status==='error'?<AlertCircle size={13}/>:<Square size={12}/>}<span>{a.label}</span></li>)}</ol></details>}{message.text&&<div className={'message-text '+(working?'streaming':'')}><Markdown remarkPlugins={[remarkGfm]} skipHtml disallowedElements={['img']} components={{a:({children})=><span className="chat-reference">{children}</span>,table:({children})=><div className="markdown-table"><table>{children}</table></div>}}>{message.role==='assistant'?message.text.replace(/\b(search_market|search_database|inspect_car|compare_cars)\b/g,name=>({search_market:'marknadssökning',search_database:'sökning i databasen',inspect_car:'annonsgranskning',compare_cars:'prisjämförelse'} as Record<string,string>)[name]):message.text}</Markdown></div>}{message.error&&message.status!=='stopped'&&<div className="message-error"><p>{message.error}</p><button onClick={retry}>Försök igen<RefreshCw size={14}/></button></div>}{working&&!message.text&&<div className="typing" aria-label="CarCrow arbetar"><i/><i/><i/></div>}</div></article>;
}
function CarGrid({items,loading,more,canLoad,selected,open,save,select}:{items:Car[];loading:boolean;more:()=>void;canLoad:boolean;selected:Car[];open:(id:string)=>void;save:(id:string)=>void;select:(car:Car)=>void}){
  const scroll=useRef<HTMLDivElement>(null),[columns,setColumns]=useState(2);
  useEffect(()=>{const el=scroll.current;if(!el)return;const observer=new ResizeObserver(entries=>setColumns(entries[0].contentRect.width>1000?3:entries[0].contentRect.width<500?1:2));observer.observe(el);return()=>observer.disconnect();},[]);
  const rowCount=Math.ceil(items.length/columns),virtual=useVirtualizer({count:rowCount+1,getScrollElement:()=>scroll.current,estimateSize:i=>i===rowCount?100:370,overscan:2}),rows=virtual.getVirtualItems();
  useEffect(()=>{const last=rows.at(-1);if(items.length&&last&&last.index>=rowCount-1&&canLoad&&!loading)more();},[rows.at(-1)?.index,rowCount,canLoad,loading]);
  return <div className="results-scroll" ref={scroll}>{!items.length&&!loading?<div className="empty-results"><CarFront size={33}/><h3>Inga matchande bilar ännu</h3>{canLoad&&<button className="button" onClick={more}>Sök nästa sida<ChevronDown size={16}/></button>}</div>:<div className="virtual-grid" style={{height:virtual.getTotalSize()}}>{rows.map(row=><div className={'virtual-row '+(row.index===rowCount?'loader-row':'')} data-index={row.index} key={row.key} ref={virtual.measureElement} style={{transform:`translateY(${row.start}px)`,gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{row.index===rowCount?<div className="load-more">{loading?<><LoaderCircle size={18} className="spin"/><span>Hämtar fler bilar…</span></>:canLoad?<button onClick={more}>Visa fler bilar<ChevronDown size={16}/></button>:items.length>0?<span>{number(items.length)} bilar visade</span>:null}</div>:items.slice(row.index*columns,(row.index+1)*columns).map(car=><CarCard key={car.id} car={car} open={()=>open(car.id)} save={()=>save(car.id)} select={()=>select(car)} selected={selected.some(c=>c.id===car.id)}/>)}</div>)}</div>}</div>;
}
function WatchDialog({filters,close,saved}:{filters:Filters;close:()=>void;saved:()=>void}){const [name,setName]=useState(filterText(filters)),[busy,setBusy]=useState(false),[error,setError]=useState('');return <Modal title="Bevaka sökning" close={close}><form className="form-content" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await call('watch',{name,filters});saved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Namn<input value={name} onChange={e=>setName(e.target.value)} required/></label>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy}>Spara bevakning<Bell size={17}/></button></form></Modal>;}
function SettingsView({boot,refresh,error,watches,failure}:{boot:Bootstrap;failure:string;refresh:()=>Promise<void>;error:(message:string)=>void;watches:()=>void}){
  const [syncing,setSyncing]=useState(false);
  return <div className="settings-content"><h1>Inställningar</h1>{failure&&<p role="alert" className="message-error">{failure}</p>}<section><h2>AI</h2><div className="setting-row"><div><strong>OpenRouter Free</strong><span>{boot.stats.aiConfigured?'Aktiverad':'Inte konfigurerad'}</span></div><span className={'connection-dot '+(boot.stats.aiConfigured?'connected':'')}/></div></section><section><div className="section-heading"><h2>Datakällor</h2><button className="icon-button" aria-label="Uppdatera datakällor" disabled={syncing} onClick={async()=>{setSyncing(true);try{await call('sync');await refresh();}catch(e){error((e as Error).message);}finally{setSyncing(false);}}}><RefreshCw size={18} className={syncing?'spin':''}/></button></div>{boot.sources.filter(s=>!!s.adapter).map(s=><div className="setting-row" key={s.id}><div><strong>{s.name}</strong><span>{s.error||(!s.enabled?'Avstängd':s.lastSync?'Uppdaterad '+relative(s.lastSync):'Ansluten')}</span></div><button className={'toggle '+(s.enabled?'on':'')} role="switch" aria-checked={s.enabled} aria-label={'Aktivera '+s.name} onClick={async()=>{try{await call('saveSource',{...s,enabled:!s.enabled});refresh();}catch(e){error((e as Error).message);}}}><i/></button></div>)}</section><section><h2>Appen</h2><div className="setting-row"><div><strong>Fortsätt i bakgrunden</strong><span>Uppdatera annonser när fönstret är stängt</span></div><button className={'toggle '+(boot.background?'on':'')} role="switch" aria-checked={boot.background} aria-label="Fortsätt i bakgrunden" onClick={async()=>{await call('settings',{background:!boot.background});refresh();}}><i/></button></div><div className="setting-row"><strong>Bevakningar</strong><button aria-label="Bevakningar" onClick={watches}>{boot.watches.length||''}<ChevronRight size={18}/></button></div><div className="setting-row"><div><strong>Exempelbilar</strong><span>Syntetiska annonser för att prova appen</span></div><button className={'toggle '+(boot.demo?'on':'')} role="switch" aria-checked={boot.demo} aria-label="Visa exempelbilar" onClick={async()=>{await call('demo',{enabled:!boot.demo});refresh();}}><i/></button></div></section></div>;
}
