import {useState} from 'react';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import {type Filters,type Bootstrap,type Car,money,number} from './types';
import {Modal,Photo} from './components';
export function FilterPanel({filters,boot,close,apply}:{filters:Filters;boot:Bootstrap;close:()=>void;apply:(f:Filters)=>void}){
  const [f,setF]=useState<Filters>({...filters});const brands=[...new Set([...boot.facets.makes,'Audi','BMW','Kia','Mercedes-Benz','Toyota','Volkswagen','Volvo'])].sort((a,b)=>a.localeCompare(b,'sv'));
  const multi=(key:'makes'|'models'|'fuelTypes',v:string)=>setF({...f,[key]:f[key]?.includes(v)?f[key]?.filter(x=>x!==v):[...(f[key]||[]),v]});
  const input=(k:keyof Filters,label:string,placeholder:string)=><label>{label}<input type="number" min="0" placeholder={placeholder} value={(f[k] as number)||''} onChange={e=>setF({...f,[k]:e.target.value?Number(e.target.value):undefined})}/></label>;
  return <Modal title="Hitta din bil" close={close} side><div className="filter-panel"><section><h3>Märke</h3><div className="choice-grid">{brands.map(x=><label className={'choice '+(f.makes?.includes(x)?'chosen':'')} key={x}><input type="checkbox" checked={!!f.makes?.includes(x)} onChange={()=>{multi('makes',x);}}/><span>{x}</span></label>)}</div></section>{!!f.makes?.length&&<section><h3>Modell</h3><div className="choice-grid">{boot.facets.models.filter(x=>f.makes?.includes(x.make)).map(x=><label className="choice" key={x.make+x.model}><input type="checkbox" checked={!!f.models?.includes(x.model)} onChange={()=>multi('models',x.model)}/><span>{x.model}</span></label>)}</div></section>}<section><h3>Pris <small>SEK</small></h3><div className="form-row">{input('minPrice','Från','0')}{input('maxPrice','Till','Ingen gräns')}</div></section><section><h3>Årsmodell</h3><div className="form-row">{input('minYear','Från','Alla år')}{input('maxYear','Till','Alla år')}</div></section><section><h3>Miltal <small>svenska mil</small></h3>{input('maxMileage','Högst','Ingen gräns')}</section><section><h3>Växellåda</h3><div className="segment">{['Alla','Automat','Manuell'].map(x=><button className={(f.gearbox||'Alla')===x?'active':''} key={x} onClick={()=>setF({...f,gearbox:x==='Alla'?undefined:x})}>{x}</button>)}</div></section><section><h3>Bränsle</h3><div className="choice-grid">{['Bensin','Diesel','El','Laddhybrid','Hybrid','Etanol','Gas'].map(x=><label className="choice" key={x}><input type="checkbox" checked={!!f.fuelTypes?.includes(x)} onChange={()=>multi('fuelTypes',x)}/><span>{x}</span></label>)}</div></section></div><div className="filter-actions"><button className="button secondary" onClick={()=>setF({sort:filters.sort})}>Återställ</button><button className="button primary" onClick={()=>apply(f)}>Visa bilar <ArrowRight size={16}/></button></div></Modal>;
}
export function Compare({cars,close,open}:{cars:Car[];close:()=>void;open:(id:string)=>void}){const rows=[['Pris',(c:Car)=>money(c.price)],['Årsmodell',(c:Car)=>String(c.year)],['Miltal',(c:Car)=>number(c.mileage)+' mil'],['Bränsle',(c:Car)=>c.fuel],['Växellåda',(c:Car)=>c.gearbox],['Ort',(c:Car)=>c.city||'Ej angiven'],['Under median',(c:Car)=>c.comparison?.percentBelow!=null?number(c.comparison.percentBelow)+' %':'För lite underlag'],['Jämförelsebilar',(c:Car)=>String(c.comparison?.sampleSize||0)]] as const;return <Modal title="Jämför dina val" close={close} wide><div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>Din kortlista</th>{cars.map(c=><th key={c.id}><div className="compare-photo"><Photo car={c}/></div><button onClick={()=>open(c.id)}>{c.make} {c.model}<ArrowUpRight size={15}/></button><small>{c.variant}</small></th>)}</tr></thead><tbody>{rows.map(([label,render])=><tr key={label}><th>{label}</th>{cars.map(c=><td key={c.id}>{render(c)}</td>)}</tr>)}</tbody></table></div><p className="compare-note small muted">Priser och egenskaper hämtas ur annonserna. Prisjämförelser kräver minst fem andra jämförbara bilar.</p></Modal>;}
