import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,MapPin,Navigation,Plus,Search,X} from 'lucide-react';
import {call,type Filters,type Bootstrap,type Car,type Place,money,number} from './types';
import {Modal,Photo} from './components';

export function MultiChoice({label,options,value=[],change,custom=false}:{label:string;options:string[];value?:string[];change:(values:string[])=>void;custom?:boolean}){
 const [query,setQuery]=useState(''),[focused,setFocused]=useState(false);
 const choices=useMemo(()=>[...new Set([...value,...options])].filter(x=>x.toLocaleLowerCase('sv').includes(query.toLocaleLowerCase('sv'))).slice(0,12),[options,value,query]);
 const toggle=(x:string)=>{change(value.includes(x)?value.filter(v=>v!==x):[...value,x]);setQuery('');};
 return <div className="multi-choice" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setFocused(false);}}><label>{label}<div className="choice-search"><Search size={16}/><input aria-label={label} value={query} placeholder={custom?'Sök eller skriv ett eget val':'Sök bland alternativen'} onFocus={()=>setFocused(true)} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const exact=choices.find(x=>x.toLowerCase()===query.trim().toLowerCase());if(exact||custom&&query.trim())toggle(exact||query.trim());}if(e.key==='Escape')setFocused(false);}}/></div></label>
 {!!value.length&&<div className="filter-chips">{value.map(x=><button type="button" key={x} onClick={()=>toggle(x)} aria-label={'Ta bort '+x}>{x}<X size={12}/></button>)}</div>}
 {focused&&<div className="choice-options">{choices.map(x=><button type="button" key={x} aria-pressed={value.includes(x)} onClick={()=>toggle(x)}><span>{x}</span>{value.includes(x)&&<Check size={14}/>}</button>)}{custom&&query.trim()&&!choices.some(x=>x.toLowerCase()===query.trim().toLowerCase())&&<button type="button" onClick={()=>toggle(query.trim())}><span>Använd ”{query.trim()}”</span><Plus size={15}/></button>}{!choices.length&&!custom&&<p>Inga alternativ matchar.</p>}<button type="button" className="choice-close" onClick={()=>setFocused(false)}>Stäng listan</button></div>}
 </div>;
}
export function LocationPicker({value,change,boot}:{value?:Place&{radiusKm?:number};change:(place:Filters['location'])=>void;boot:Bootstrap}){
 const [query,setQuery]=useState(value?.label||''),[places,setPlaces]=useState<Place[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(boot.locationConsent);
 useEffect(()=>{let valid=true;const timer=setTimeout(()=>call<Place[]>('places',{query}).then(p=>{if(valid)setPlaces(p);}).catch(()=>{}),120);return()=>{valid=false;clearTimeout(timer);};},[query]);
 async function locate(){setBusy(true);setError('');try{await call('locationConsent',{enabled:true});setConsent(true);const p=await call<Place>('approximateLocation');change({...p,radiusKm:value?.radiusKm});setQuery(p.label);setOpen(false);}catch(e){setError((e as Error).message||'Platsen kunde inte hämtas. Välj en ort i stället.');}finally{setBusy(false);}}
 return <div className="location-picker"><label>Utgå från en ort<div className="choice-search"><MapPin size={16}/><input aria-label="Sök ort" placeholder="Till exempel Göteborg" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);}}/></div></label>{open&&<div className="choice-options">{places.map(p=><button type="button" key={p.placeId} onClick={()=>{change({...p,radiusKm:value?.radiusKm});setQuery(p.label);setOpen(false);}}><span>{p.label}</span><small>{p.latitude.toFixed(2)}, {p.longitude.toFixed(2)}</small></button>)}{!places.length&&<p>Välj en annan stavning på orten.</p>}</div>}
 {value&&<><div className="filter-chips"><button type="button" onClick={()=>{change(undefined);setQuery('');}}>{value.label}<X size={12}/></button></div><label>Sök inom<select aria-label="Sökavstånd" value={value.radiusKm||''} onChange={e=>change({...value,radiusKm:e.target.value?Number(e.target.value):undefined})}><option value="">Hela Sverige · visa avstånd</option>{[25,50,100,200,300,500,1000].map(km=><option value={km} key={km}>{km} km</option>)}</select></label></>}
 <div className="location-consent"><p>Din ungefärliga ort hämtas via internetanslutningen. Kontrollera orten, särskilt om du använder VPN. AI:n får bara ortens namn. Avstånd beräknas på datorn. Du kan stänga av platsdelningen här.</p><button type="button" className="button secondary" disabled={busy} onClick={locate}><Navigation size={16}/>{busy?'Hämtar din plats…':'Använd ungefärlig plats'}</button>{consent&&<button type="button" className="text-button" onClick={async()=>{await call('locationConsent',{enabled:false});setConsent(false);change(undefined);setQuery('');}}>Stäng av platsdelning</button>}</div>{error&&<p className="message-error" role="alert">{error}</p>}<p className="small muted">Avstånd är fågelvägen och ungefärliga när annonsen bara anger en ort.</p></div>;
}
export function FilterPanel({filters,boot,close,apply}:{filters:Filters;boot:Bootstrap;close:()=>void;apply:(f:Filters)=>void}){
 const [f,setF]=useState<Filters>({...filters}),[tab,setTab]=useState('bil'),[error,setError]=useState('');
 const options=useMemo(()=>boot.facets.models.filter(x=>!f.makes?.length||f.makes.some(m=>m.toLowerCase()===x.make.toLowerCase())).map(x=>x.model),[boot.facets.models,f.makes]);
 const input=(k:keyof Filters,label:string,placeholder:string)=><label>{label}<input type="number" min="0" placeholder={placeholder} value={(f[k] as number)??''} onChange={e=>setF({...f,[k]:e.target.value?Number(e.target.value):undefined})}/></label>;
 const multi=(key:'makes'|'models'|'fuelTypes'|'bodyTypes'|'sources',v:string[])=>setF({...f,[key]:v.length?v:undefined});
 return <Modal title="Anpassa din sökning" close={close} side><div className="filter-tabs" role="tablist" aria-label="Filtergrupper">{[['bil','Bilen'],['plats','Plats'],['fler','Fler val']].map(([id,label])=><button type="button" role="tab" aria-selected={tab===id} className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="filter-panel modern-filters" role="tabpanel">
 {tab==='bil'&&<><section><MultiChoice label="Märken" options={boot.facets.makes} value={f.makes} custom change={v=>multi('makes',v)}/><MultiChoice label="Modeller" options={options} value={f.models} custom change={v=>multi('models',v)}/><p className="small muted">Du kan välja flera eller skriva in ett märke eller en modell som saknas.</p></section><section><h3>Pris <small>SEK</small></h3><div className="form-row">{input('minPrice','Från','0')}{input('maxPrice','Till','Ingen gräns')}</div></section><section><h3>Årsmodell</h3><div className="form-row">{input('minYear','Från','Alla år')}{input('maxYear','Till','Alla år')}</div></section><section><h3>Miltal <small>svenska mil</small></h3><div className="form-row">{input('minMileage','Från','0')}{input('maxMileage','Till','Ingen gräns')}</div></section></>}
 {tab==='plats'&&<section><LocationPicker boot={boot} value={f.location} change={location=>setF({...f,location,sort:!location&&f.sort==='distance'?'newest':f.sort})}/>{f.location&&<label className="choice"><input type="checkbox" checked={f.sort==='distance'} onChange={e=>setF({...f,sort:e.target.checked?'distance':'newest'})}/>Närmaste bilar först</label>}</section>}
 {tab==='fler'&&<><section><h3>Växellåda</h3><div className="segment">{['Alla','Automat','Manuell'].map(x=><button type="button" className={(f.gearbox||'Alla')===x?'active':''} key={x} onClick={()=>setF({...f,gearbox:x==='Alla'?undefined:x})}>{x}</button>)}</div></section><section><MultiChoice label="Bränsle" options={boot.facets.fuels} value={f.fuelTypes} change={v=>multi('fuelTypes',v)}/><MultiChoice label="Kaross" options={['Kombi','Halvkombi','Sedan','SUV','Coupé','Cabriolet','Pickup','Minibuss']} value={f.bodyTypes} change={v=>multi('bodyTypes',v)}/></section><section><h3>Säljare och annonser</h3><label>Säljare<select aria-label="Typ av säljare" value={f.sellerType||''} onChange={e=>setF({...f,sellerType:e.target.value as Filters['sellerType']||undefined})}><option value="">Alla</option><option value="dealer">Bilhandlare</option><option value="private">Privatpersoner</option></select></label><label>Publicerad<select value={f.publishedWithinDays||''} onChange={e=>setF({...f,publishedWithinDays:e.target.value?Number(e.target.value):undefined})}><option value="">När som helst</option>{[1,3,7,14,30].map(n=><option value={n} key={n}>Senaste {n===1?'dygnet':n+' dagarna'}</option>)}</select></label><label className="choice"><input type="checkbox" checked={!!f.hasImages} onChange={e=>setF({...f,hasImages:e.target.checked||undefined})}/>Bara annonser med bilder</label></section><section><h3>Datakällor</h3><div className="choice-grid">{boot.sources.filter(s=>s.adapter&&s.enabled).map(s=><label className="choice" key={s.id}><input type="checkbox" checked={!!f.sources?.includes(s.id)} onChange={()=>multi('sources',f.sources?.includes(s.id)?f.sources.filter(x=>x!==s.id):[...(f.sources||[]),s.id])}/>{s.name}</label>)}</div><p className="small muted">Alla aktiva källor används om du inte väljer någon.</p></section></>}
 {error&&<p role="alert" className="message-error">{error}</p>}</div><div className="filter-actions"><button className="button secondary" onClick={()=>{setF({sort:filters.sort==='distance'?'newest':filters.sort});setError('');}}>Återställ</button><button className="button primary" onClick={async()=>{try{const valid=await call<Filters>('validateFilters',{filters:f});apply(valid);}catch(e){setError((e as Error).message);}}}>Visa bilar <ArrowRight size={16}/></button></div></Modal>;
}
export function Compare({cars,close,open}:{cars:Car[];close:()=>void;open:(id:string)=>void}){const rows=[['Pris',(c:Car)=>money(c.price)],['Årsmodell',(c:Car)=>c.year==null?'Ej angiven':String(c.year)],['Miltal',(c:Car)=>c.mileage==null?'Ej angivet':number(c.mileage)+' mil'],['Bränsle',(c:Car)=>c.fuel||'Ej angivet'],['Växellåda',(c:Car)=>c.gearbox||'Ej angiven'],['Ort',(c:Car)=>c.city||'Ej angiven'],['Under median',(c:Car)=>c.comparison?.percentBelow!=null?number(c.comparison.percentBelow)+' %':'För lite underlag'],['Jämförelsebilar',(c:Car)=>String(c.comparison?.sampleSize||0)]] as const;return <Modal title="Jämför dina val" close={close} wide><div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>Din kortlista</th>{cars.map(c=><th key={c.id}><div className="compare-photo"><Photo car={c}/></div><button onClick={()=>open(c.id)}>{c.make} {c.model}<ArrowUpRight size={15}/></button><small>{c.variant}</small></th>)}</tr></thead><tbody>{rows.map(([label,render])=><tr key={label}><th>{label}</th>{cars.map(c=><td key={c.id}>{render(c)}</td>)}</tr>)}</tbody></table></div><p className="compare-note small muted">Priser och egenskaper hämtas ur annonserna. Prisjämförelser kräver minst fem andra jämförbara bilar.</p></Modal>;}
