export type Filters={makes?:string[];models?:string[];minPrice?:number;maxPrice?:number;minYear?:number;maxYear?:number;maxMileage?:number;fuelTypes?:string[];gearbox?:string;query?:string;sort?:string};
export type Peer={id:string;title:string;price:number;year:number;mileage:number};
export type Comparison={sampleSize:number;median:number|null;percentBelow:number|null;peers:Peer[];reason:string};
export type Offer={id:string;sourceId:string;source:string;price:number;url:string;lastSeen:string};
export type Car={id:string;listingId:string;title:string;make:string;model:string;variant:string;bodyType:string;price:number;year:number;mileage:number;fuel:string;gearbox:string;city:string;seller:string;description:string;images:string[];color?:string;source:string;offers:Offer[];lastSeen:string;firstSeen:string;publishedAt:string;demo:boolean;saved:boolean;active?:boolean;recommendation?:{score:number;reason:string;model:string};comparison?:Comparison;history?:{id:number;kind:string;at:string;old_price:number|null;new_price:number|null;source:string}[]};
export type Source={id:string;name:string;enabled:boolean;adapter?:string;lastSync:string|null;error:string|null;feedURL?:string;approval?:string;approvedUntil?:string;mediaAllowed?:boolean;intervalMinutes?:number;retentionDays?:number;hosts:string[];hasToken?:boolean;docs?:string};
export type Watch={id:string;name:string;filters:Filters;total:number;newCount:number;checkedAt:string|null;error:string|null};
export type Bootstrap={stats:{listings:number;vehicles:number;updated:string|null;aiConfigured:boolean;model:string;sources:Source[]};facets:{makes:string[];models:{make:string;model:string}[];fuels:string[]};demo:boolean;theme:'light'|'dark'|'system';dark:boolean;checkingWatches:boolean;sources:Source[];watches:Watch[];platform:string};
export type SearchResult={items:Car[];total:number;page:number;remaining?:number;sessionId?:string;hasMore?:boolean;limited?:boolean;filters?:Filters;summary?:string;description?:string;intent?:string;model?:string;sourceWarning?:string|null};
export type Activity={id:string;label:string;status:'running'|'done'|'error'|'stopped'};
export type Message={id:string;role:'user'|'assistant';text:string;status?:'running'|'done'|'error'|'stopped';error?:string;activities?:Activity[];startedAt?:string};
export type Chat={id:string;title:string;messages:Message[];filters:Filters;cars:Car[];sessionId?:string;hasMore?:boolean;total?:number;remaining?:number;comparison?:boolean;coverage?:Record<string,unknown>};
export type AgentEvent={type:string;chatId:string;runId:string;messageId:string;delta?:string;text?:string;activity?:Activity;source?:string;status?:Activity['status'];label?:string;error?:string;result?:SearchResult&{hasMore?:boolean;comparison?:boolean};chat?:Chat;model?:string};
declare global{interface Window{carcrow:{call:(action:string,payload?:unknown)=>Promise<{ok:boolean;data?:unknown;error?:string}>;onChanged:(callback:()=>void)=>()=>void;onAgent:(callback:(e:AgentEvent)=>void)=>()=>void;onMarket:(callback:(e:{source:string;label:string;status:Activity['status']})=>void)=>()=>void}}}
export async function call<T>(action:string,payload:unknown={}):Promise<T>{if(!window.carcrow)throw new Error('Öppna CarCrow som skrivbordsapp.');const result=await window.carcrow.call(action,payload);if(!result.ok)throw new Error(result.error||'Något gick fel.');return result.data as T;}
export const number=(n:number)=>n.toLocaleString('sv-SE');
export const money=(n:number)=>number(n)+' kr';
export function relative(date:string|null|undefined){if(!date)return 'Inte ansluten';const mins=Math.max(0,Math.floor((Date.now()-Date.parse(date))/60000));if(mins<1)return 'nyss';if(mins<60)return `${mins} min sedan`;if(mins<1440)return `${Math.floor(mins/60)} h sedan`;return `${Math.floor(mins/1440)} dagar sedan`;}
export function filterText(f:Filters){return [f.makes?.join(' eller '),f.models?.join(' eller '),f.maxPrice!=null?`Max ${money(f.maxPrice)}`:null,f.minPrice!=null&&f.minPrice>0?`Min ${money(f.minPrice)}`:null,f.gearbox,f.maxMileage!=null?`Max ${number(f.maxMileage)} mil`:null,f.fuelTypes?.length===7?null:f.fuelTypes?.join(', '),f.minYear?`Från ${f.minYear}`:null,f.maxYear?`Till ${f.maxYear}`:null,f.query].filter(Boolean).join(' · ')||'Alla bilar';}
